# Generated by Django 6.0.6 on 2026-07-07 14:06

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("sandbox_envs", "0006_drop_network_enabled"),
        ("schedules", "0015_schedules_agent_override_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("thread_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("api_job", "API Run"),
                            ("mcp_job", "MCP Run"),
                            ("schedule", "Scheduled Run"),
                            ("ui_job", "UI Run"),
                            ("issue_webhook", "Issue Webhook"),
                            ("mr_webhook", "MR/PR Webhook"),
                        ],
                        max_length=20,
                        verbose_name="origin",
                    ),
                ),
                (
                    "external_username",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="external username"),
                ),
                ("repo_id", models.CharField(max_length=255, verbose_name="repository")),
                ("ref", models.CharField(blank=True, default="", max_length=255, verbose_name="branch / ref")),
                ("title", models.CharField(blank=True, default="", max_length=120, verbose_name="title")),
                ("agent_model", models.CharField(blank=True, default="", max_length=255, verbose_name="agent model")),
                (
                    "agent_thinking_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimal", "Minimal"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("xhigh", "Extra high"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="agent thinking level",
                    ),
                ),
                ("issue_iid", models.PositiveIntegerField(blank=True, null=True, verbose_name="issue IID")),
                (
                    "merge_request_iid",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="merge request IID"),
                ),
                ("active_run_id", models.CharField(blank=True, default=None, max_length=64, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="created at"),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="last active at"),
                ),
                (
                    "sandbox_environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_sessions",
                        to="sandbox_envs.sandboxenvironment",
                        verbose_name="sandbox environment",
                    ),
                ),
                (
                    "scheduled_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_sessions",
                        to="schedules.scheduledjob",
                        verbose_name="scheduled job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={"verbose_name": "Session", "verbose_name_plural": "Sessions", "ordering": ["-last_active_at"]},
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("api_job", "API Run"),
                            ("mcp_job", "MCP Run"),
                            ("schedule", "Scheduled Run"),
                            ("ui_job", "UI Run"),
                            ("issue_webhook", "Issue Webhook"),
                            ("mr_webhook", "MR/PR Webhook"),
                        ],
                        max_length=20,
                        verbose_name="trigger type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("READY", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "external_username",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="external username"),
                ),
                ("title", models.CharField(blank=True, default="", max_length=120, verbose_name="title")),
                ("batch_id", models.UUIDField(blank=True, db_index=True, null=True, verbose_name="batch ID")),
                ("repo_id", models.CharField(max_length=255, verbose_name="repository")),
                ("ref", models.CharField(blank=True, default="", max_length=255, verbose_name="branch / ref")),
                ("prompt", models.TextField(blank=True, default="", verbose_name="prompt")),
                ("agent_model", models.CharField(blank=True, default="", max_length=255, verbose_name="agent model")),
                (
                    "agent_thinking_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimal", "Minimal"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("xhigh", "Extra high"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="agent thinking level",
                    ),
                ),
                (
                    "notify_on",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "Never"),
                            ("always", "Always"),
                            ("on_success", "On success only"),
                            ("on_failure", "On failure only"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="notify on",
                    ),
                ),
                (
                    "mention_comment_id",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="mention comment ID"),
                ),
                (
                    "merge_request_iid",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="merge request IID"),
                ),
                (
                    "merge_request_web_url",
                    models.URLField(blank=True, default="", max_length=500, verbose_name="merge request URL"),
                ),
                ("result_summary", models.TextField(blank=True, default="", verbose_name="result summary")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="error message")),
                ("code_changes", models.BooleanField(default=False, verbose_name="code changes")),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True, verbose_name="input tokens")),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True, verbose_name="output tokens")),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True, verbose_name="total tokens")),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True, verbose_name="cost (USD)"
                    ),
                ),
                ("usage_by_model", models.JSONField(blank=True, null=True, verbose_name="usage by model")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="created at"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="started at")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="finished at")),
                (
                    "sandbox_environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="sandbox_envs.sandboxenvironment",
                        verbose_name="sandbox environment",
                    ),
                ),
                (
                    "task_result",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run",
                        to="django_tasks_database.dbtaskresult",
                        verbose_name="task result",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="agent_sessions.session",
                        verbose_name="session",
                    ),
                ),
            ],
            options={"verbose_name": "Run", "verbose_name_plural": "Runs", "ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="session", index=models.Index(fields=["user", "-last_active_at"], name="session_user_active_idx")
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["origin", "-last_active_at"], name="session_origin_active_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["repo_id", "-last_active_at"], name="session_repo_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("active_run_id__isnull", True), models.Q(("active_run_id", ""), _negated=True), _connector="OR"
                ),
                name="session_active_run_id_nonempty",
            ),
        ),
        migrations.AddIndex(
            model_name="run", index=models.Index(fields=["session", "-created_at"], name="run_session_created_idx")
        ),
        migrations.AddIndex(
            model_name="run", index=models.Index(fields=["trigger_type", "-created_at"], name="run_trigger_created_idx")
        ),
        migrations.AddIndex(
            model_name="run", index=models.Index(fields=["status", "-created_at"], name="run_status_created_idx")
        ),
        migrations.AddIndex(
            model_name="run", index=models.Index(fields=["user", "-created_at"], name="run_user_created_idx")
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["READY", "RUNNING"]), ("trigger_type__in", ["api_job", "mcp_job"])),
                fields=("session",),
                name="run_one_active_per_session",
            ),
        ),
    ]
