# Generated by Django 6.0.7 on 2026-07-15 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0003_run_message_id")]

    operations = [
        migrations.CreateModel(
            name="RunEnvelope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("all-clear", "All clear"),
                            ("found-issues", "Found issues"),
                            ("needs-attention", "Needs attention"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="count")),
                ("summary", models.TextField(blank=True, default="", verbose_name="summary")),
                ("actionable", models.JSONField(blank=True, default=list, verbose_name="actionable")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="created at"),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envelope",
                        to="agent_sessions.run",
                        verbose_name="run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run Envelope",
                "verbose_name_plural": "Run Envelopes",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["all-clear", "found-issues", "needs-attention", "failed"])),
                        name="run_envelope_status_valid",
                    )
                ],
            },
        )
    ]
