# Generated by Django 6.0.6 on 2026-07-08 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_sessions", "0003_enum_check_constraints"),
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("sandbox_envs", "0006_drop_network_enabled"),
        ("schedules", "0016_alter_scheduledjob_agent_thinking_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("agent_thinking_level", ""),
                    ("agent_thinking_level__in", ["minimal", "low", "medium", "high", "xhigh"]),
                    _connector="OR",
                ),
                name="run_agent_thinking_level_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("notify_on__isnull", True),
                    ("notify_on__in", ["never", "always", "on_success", "on_failure"]),
                    _connector="OR",
                ),
                name="run_notify_on_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("agent_thinking_level", ""),
                    ("agent_thinking_level__in", ["minimal", "low", "medium", "high", "xhigh"]),
                    _connector="OR",
                ),
                name="session_agent_thinking_level_valid",
            ),
        ),
    ]
