# Generated by Django 6.0.6 on 2026-07-08 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_sessions", "0003_run_message_id"),
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("sandbox_envs", "0006_drop_network_enabled"),
        ("schedules", "0016_alter_scheduledjob_agent_thinking_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "trigger_type__in",
                    ["chat", "api_job", "mcp_job", "schedule", "ui_job", "issue_webhook", "mr_webhook"],
                )),
                name="run_trigger_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["QUEUED", "READY", "RUNNING", "SUCCESSFUL", "FAILED"])),
                name="run_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "origin__in",
                    ["chat", "api_job", "mcp_job", "schedule", "ui_job", "issue_webhook", "mr_webhook"],
                )),
                name="session_origin_valid",
            ),
        ),
    ]
