# Generated by Django 6.0.7 on 2026-08-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0004_runenvelope")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="mcp_overrides",
            field=models.JSONField(blank=True, default=dict, verbose_name="MCP overrides"),
        )
    ]
