# Generated by Django 6.0.7 on 2026-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0004_runenvelope")]

    operations = [
        migrations.AddField(
            model_name="run",
            name="muted",
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name="muted"),
        )
    ]
