# Generated by Django 6.0.7 on 2026-07-09 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_sessions", "0005_more_enum_check_constraints"),
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("sandbox_envs", "0006_drop_network_enabled"),
        ("schedules", "0016_alter_scheduledjob_agent_thinking_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="run", name="run_one_active_per_session"),
        migrations.RemoveConstraint(model_name="run", name="run_trigger_type_valid"),
        migrations.RemoveConstraint(model_name="session", name="session_origin_valid"),
        migrations.AddField(
            model_name="run",
            name="continuation_of_batch_id",
            field=models.UUIDField(
                blank=True,
                help_text="Set on the coordinator continuation run enqueued when this batch turned terminal.",
                null=True,
                verbose_name="continuation of batch",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="parent_thread_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Coordinator thread that delegated this session's first run via delegate_jobs; empty for top-level sessions.",
                max_length=64,
                null=True,
                verbose_name="parent thread ID",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="spawn_depth",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 = human/system-triggered; +1 per delegate_jobs hop. Capped by MAX_SPAWN_DEPTH.",
                verbose_name="spawn depth",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("api_job", "API Run"),
                    ("mcp_job", "MCP Run"),
                    ("schedule", "Scheduled Run"),
                    ("ui_job", "UI Run"),
                    ("issue_webhook", "Issue Webhook"),
                    ("mr_webhook", "MR/PR Webhook"),
                    ("delegated_job", "Delegated Run"),
                ],
                max_length=20,
                verbose_name="trigger type",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="origin",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("api_job", "API Run"),
                    ("mcp_job", "MCP Run"),
                    ("schedule", "Scheduled Run"),
                    ("ui_job", "UI Run"),
                    ("issue_webhook", "Issue Webhook"),
                    ("mr_webhook", "MR/PR Webhook"),
                    ("delegated_job", "Delegated Run"),
                ],
                max_length=20,
                verbose_name="origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["READY", "RUNNING"]), ("trigger_type__in", ["api_job", "mcp_job", "delegated_job"])
                ),
                fields=("session",),
                name="run_one_active_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                condition=models.Q(("continuation_of_batch_id__isnull", False)),
                fields=("continuation_of_batch_id",),
                name="run_one_continuation_per_batch",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "trigger_type__in",
                    [
                        "chat",
                        "api_job",
                        "mcp_job",
                        "schedule",
                        "ui_job",
                        "issue_webhook",
                        "mr_webhook",
                        "delegated_job",
                    ],
                )),
                name="run_trigger_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "origin__in",
                    [
                        "chat",
                        "api_job",
                        "mcp_job",
                        "schedule",
                        "ui_job",
                        "issue_webhook",
                        "mr_webhook",
                        "delegated_job",
                    ],
                )),
                name="session_origin_valid",
            ),
        ),
    ]
