# Generated by Django 6.0.7 on 2026-07-09 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_sessions", "0005_delegate_jobs_fields"),
        ("sandbox_envs", "0006_drop_network_enabled"),
        ("schedules", "0016_alter_scheduledjob_agent_thinking_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="parent_thread_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Coordinator thread that delegated this session's first run via delegate_jobs; unset (NULL) for top-level sessions.",
                max_length=64,
                null=True,
                verbose_name="parent thread ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("spawn_depth__lte", 2)), name="session_spawn_depth_within_cap"
            ),
        ),
    ]
