# Generated by Django 6.0.7 on 2026-08-25 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_sessions", "0006_run_muted_classify_eligible"),
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("sandbox_envs", "0006_drop_network_enabled"),
        ("schedules", "0019_muted_drop_notify_on"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="run", name="run_trigger_type_valid"),
        migrations.RemoveConstraint(model_name="session", name="session_origin_valid"),
        migrations.AddField(
            model_name="session",
            name="watch_armed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="watch armed at"),
        ),
        migrations.AddField(
            model_name="session",
            name="watch_attempts",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="watch attempts"),
        ),
        migrations.AddField(
            model_name="session",
            name="watch_pipeline_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="last watched pipeline"),
        ),
        migrations.AddField(
            model_name="session",
            name="watch_state",
            field=models.CharField(
                choices=[
                    ("off", "Not watching"),
                    ("watching", "Waiting for CI"),
                    ("fixing", "Fixing"),
                    ("green", "Green"),
                    ("exhausted", "Attempts exhausted"),
                    ("unclear", "CI unreadable"),
                ],
                default="off",
                max_length=10,
                verbose_name="watch state",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("api_job", "API Run"),
                    ("mcp_job", "MCP Run"),
                    ("schedule", "Scheduled Run"),
                    ("ui_job", "UI Run"),
                    ("issue_webhook", "Issue Webhook"),
                    ("mr_webhook", "MR/PR Webhook"),
                    ("pipeline_webhook", "Pipeline Webhook"),
                ],
                max_length=20,
                verbose_name="trigger type",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="origin",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("api_job", "API Run"),
                    ("mcp_job", "MCP Run"),
                    ("schedule", "Scheduled Run"),
                    ("ui_job", "UI Run"),
                    ("issue_webhook", "Issue Webhook"),
                    ("mr_webhook", "MR/PR Webhook"),
                    ("pipeline_webhook", "Pipeline Webhook"),
                ],
                max_length=20,
                verbose_name="origin",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["repo_id", "ref", "watch_state"], name="session_watch_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                condition=models.Q(("watch_state__in", ["fixing", "watching"])),
                fields=["watch_armed_at"],
                name="session_watch_sweep_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "trigger_type__in",
                    [
                        "chat",
                        "api_job",
                        "mcp_job",
                        "schedule",
                        "ui_job",
                        "issue_webhook",
                        "mr_webhook",
                        "pipeline_webhook",
                    ],
                )),
                name="run_trigger_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "origin__in",
                    [
                        "chat",
                        "api_job",
                        "mcp_job",
                        "schedule",
                        "ui_job",
                        "issue_webhook",
                        "mr_webhook",
                        "pipeline_webhook",
                    ],
                )),
                name="session_origin_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("watch_state__in", ["off", "watching", "fixing", "green", "exhausted", "unclear"])),
                name="session_watch_state_valid",
            ),
        ),
    ]
