# Generated by Django 6.0.7 on 2026-08-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0006_run_muted_classify_eligible")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="external_refs",
            field=models.JSONField(blank=True, default=list, verbose_name="external references"),
        )
    ]
