# Generated by Django 6.0.7 on 2026-08-09 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0006_backfill_run_muted")]

    operations = [
        migrations.RemoveConstraint(model_name="run", name="run_notify_on_valid"),
        migrations.RemoveField(model_name="run", name="notify_on"),
    ]
