# Generated by Django 6.0.7 on 2026-07-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0007_session_spawn_depth_cap")]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("READY", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESSFUL", "Done"),
                    ("FAILED", "Failed"),
                ],
                default="READY",
                max_length=10,
                verbose_name="status",
            ),
        )
    ]
