# Generated by Django 6.0.7 on 2026-07-13 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0003_run_message_id"), ("agent_sessions", "0007_alter_run_status")]

    operations = []
