# Generated by Django 6.0.7 on 2026-08-20 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0005_session_mcp_overrides"), ("agent_sessions", "0007_drop_notify_on")]

    operations = []
