# Generated by Django 6.1 on 2026-09-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0008_session_pipeline_watch")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="acting_platform_uid",
            field=models.CharField(blank=True, default="", max_length=191, verbose_name="acting platform user ID"),
        )
    ]
