# Generated by Django 6.1.1 on 2026-09-26 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_sessions", "0008_session_pipeline_watch"),
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("sandbox_envs", "0006_drop_network_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="run", name="question", field=models.JSONField(blank=True, null=True, verbose_name="question")
        ),
        migrations.RemoveConstraint(model_name="run", name="run_status_valid"),
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("READY", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESSFUL", "Done"),
                    ("WAITING_INPUT", "Needs input"),
                    ("FAILED", "Failed"),
                ],
                default="READY",
                max_length=13,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "status__in",
                    ["QUEUED", "READY", "RUNNING", "SUCCESSFUL", "WAITING_INPUT", "FAILED"],
                )),
                name="run_status_valid",
            ),
        ),
    ]
