# Generated by Django 6.1.1 on 2026-09-24 16:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sessions.models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0008_session_pipeline_watch")]

    operations = [
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("filename", models.CharField(max_length=255, verbose_name="filename")),
                ("content_type", models.CharField(max_length=100, verbose_name="content type")),
                ("size", models.PositiveBigIntegerField(verbose_name="size")),
                (
                    "file",
                    models.FileField(max_length=500, upload_to=sessions.models.artifact_upload_to, verbose_name="file"),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="created at"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="agent_sessions.run",
                        verbose_name="run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run Artifact",
                "verbose_name_plural": "Run Artifacts",
                "ordering": ["created_at", "id"],
            },
        )
    ]
