# Generated by Django 6.1.1 on 2026-09-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0009_run_status_waiting_input")]

    operations = [
        migrations.RemoveConstraint(model_name="runenvelope", name="run_envelope_status_valid"),
        migrations.AlterField(
            model_name="runenvelope",
            name="status",
            field=models.CharField(
                choices=[
                    ("all-clear", "All clear"),
                    ("found-issues", "Found issues"),
                    ("needs-attention", "Needs attention"),
                    ("needs-input", "Needs input"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="runenvelope",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "status__in",
                    ["all-clear", "found-issues", "needs-attention", "needs-input", "failed"],
                )),
                name="run_envelope_status_valid",
            ),
        ),
    ]
