# Generated by Django 6.1.1 on 2026-09-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0011_runartifact")]

    operations = [
        migrations.AddField(
            model_name="run",
            name="clone_seconds",
            field=models.FloatField(blank=True, null=True, verbose_name="clone seconds"),
        ),
        migrations.AddField(
            model_name="run",
            name="sandbox_acquisition",
            field=models.CharField(blank=True, default="", max_length=16, verbose_name="sandbox acquisition"),
        ),
    ]
