# Generated by Django 6.1.1 on 2026-10-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0012_run_clone_seconds_sandbox_acquisition")]

    operations = [
        migrations.AddField(
            model_name="runartifact",
            name="revised_by",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="revised_artifacts",
                to="agent_sessions.run",
                verbose_name="revised by",
            ),
        ),
        migrations.AddField(
            model_name="runartifact",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="updated at"),
        ),
    ]
