# Generated by Django 6.1.1 on 2026-10-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0012_run_clone_seconds_sandbox_acquisition")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="cross_project_user_ids",
            field=models.JSONField(blank=True, default=list, editable=False, verbose_name="cross-project users"),
        )
    ]
