# Generated by Django 6.1.1 on 2026-10-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0012_run_clone_seconds_sandbox_acquisition")]

    operations = [
        migrations.AddField(
            model_name="runartifact",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="updated at"),
        )
    ]
