# Generated by Django 6.1.1 on 2026-10-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0013_runartifact_updated_at")]

    operations = [
        migrations.AddField(
            model_name="runartifact",
            name="revised_by",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="revised_artifacts",
                to="agent_sessions.run",
                verbose_name="revised by",
            ),
        )
    ]
