# Generated by Django 6.0.5 on 2026-05-25 17:54

import re

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "name",
                    models.SlugField(
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(regex=re.compile("^[a-z0-9][a-z0-9-]{0,79}$"))
                        ],
                        verbose_name="name",
                    ),
                ),
                ("description", models.CharField(blank=True, default="", max_length=1024, verbose_name="description")),
                (
                    "source",
                    models.CharField(
                        choices=[("builtin", "Built-in"), ("custom", "Custom")],
                        default="custom",
                        max_length=10,
                        verbose_name="source",
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[("http", "HTTP (streamable)"), ("sse", "SSE")], max_length=10, verbose_name="transport"
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                ("_headers_encrypted", models.TextField(blank=True, editable=False, null=True)),
                (
                    "tool_filter_mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("allow", "Allow only listed tools"),
                            ("block", "Block listed tools"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="tool filter mode",
                    ),
                ),
                ("tool_filter_items", models.JSONField(blank=True, default=list, verbose_name="tool filter items")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        )
    ]
