# Generated by Django 6.0.5 on 2026-05-25 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp_servers", "0002_import_legacy_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mcpserver",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tool_filter_mode", "none"), models.Q(("tool_filter_items", []), _negated=True), _connector="OR"
                ),
                name="mcp_tool_filter_items_required_when_mode_set",
            ),
        )
    ]
