# Generated by Django 6.0.7 on 2026-07-15 14:51

from django.db import migrations, models

import mcp_servers.validators


class Migration(migrations.Migration):
    dependencies = [("mcp_servers", "0005_mcpserver_tool_snapshot")]

    operations = [
        migrations.AlterField(
            model_name="mcpserver",
            name="url",
            field=models.CharField(
                max_length=200, validators=[mcp_servers.validators.validate_http_url], verbose_name="URL"
            ),
        )
    ]
