# Generated by Django 6.0.7 on 2026-07-13 11:16

import re

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp_servers", "0006_alter_mcpserver_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="scope",
            field=models.CharField(
                choices=[("global", "Global"), ("user", "User")], default="global", max_length=10, verbose_name="scope"
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_mcp_servers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mcpserver",
            name="name",
            field=models.SlugField(
                max_length=80,
                validators=[django.core.validators.RegexValidator(regex=re.compile("^[a-z0-9][a-z0-9-]{0,79}$"))],
                verbose_name="name",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpserver",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "global")), fields=("name",), name="mcp_global_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpserver",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "user")), fields=("user", "name"), name="mcp_user_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpserver",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "user"), ("user__isnull", False)),
                    models.Q(("scope", "global"), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="mcp_scope_user_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpserver",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", "builtin"), ("scope", "user"), _negated=True),
                name="mcp_builtin_is_global",
            ),
        ),
    ]
