# Generated by Django 6.0.7 on 2026-08-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mcp_servers", "0007_per_user_servers")]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("on-demand", "On-demand"), ("disabled", "Disabled")],
                default="active",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpserver",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "on-demand", "disabled"])), name="mcp_server_status_valid"
            ),
        ),
    ]
