# Generated by Django 6.0.7 on 2026-08-08 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("mcp_servers", "0009_backfill_status_from_enabled")]

    operations = [migrations.RemoveField(model_name="mcpserver", name="enabled")]
