# Generated by Django 6.0.3 on 2026-04-01 14:18

from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MergeMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("repo_id", models.CharField(db_index=True, max_length=255, verbose_name="repository ID")),
                ("merge_request_iid", models.PositiveIntegerField(verbose_name="merge request IID")),
                ("title", models.CharField(blank=True, max_length=512, verbose_name="title")),
                ("lines_added", models.PositiveIntegerField(default=0, verbose_name="lines added")),
                ("lines_removed", models.PositiveIntegerField(default=0, verbose_name="lines removed")),
                ("files_changed", models.PositiveIntegerField(default=0, verbose_name="files changed")),
                ("daiv_lines_added", models.PositiveIntegerField(default=0, verbose_name="DAIV lines added")),
                ("daiv_lines_removed", models.PositiveIntegerField(default=0, verbose_name="DAIV lines removed")),
                ("human_lines_added", models.PositiveIntegerField(default=0, verbose_name="human lines added")),
                ("human_lines_removed", models.PositiveIntegerField(default=0, verbose_name="human lines removed")),
                ("total_commits", models.PositiveIntegerField(default=0, verbose_name="total commits")),
                ("daiv_commits", models.PositiveIntegerField(default=0, verbose_name="DAIV commits")),
                ("merged_at", models.DateTimeField(verbose_name="merged at")),
                ("target_branch", models.CharField(max_length=255, verbose_name="target branch")),
                ("source_branch", models.CharField(max_length=255, verbose_name="source branch")),
                (
                    "platform",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")], max_length=10, verbose_name="platform"
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge Metric",
                "verbose_name_plural": "Merge Metrics",
                "indexes": [
                    models.Index(fields=["repo_id", "merged_at"], name="codebase_me_repo_id_e566b3_idx"),
                    models.Index(fields=["merged_at"], name="codebase_me_merged__2d600f_idx"),
                ],
                "unique_together": {("repo_id", "merge_request_iid", "platform")},
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(daiv_commits__lte=models.F("total_commits")), name="daiv_lte_total_commits"
                    )
                ],
            },
        )
    ]
