# Generated by Django 6.0.6 on 2026-07-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("codebase", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="RepositoryAccessSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_started_at", models.DateTimeField(blank=True, null=True, verbose_name="last started at")),
                ("last_success_at", models.DateTimeField(blank=True, null=True, verbose_name="last success at")),
                (
                    "status",
                    models.CharField(
                        choices=[("never", "Never synced"), ("ok", "OK"), ("failed", "Failed")],
                        default="never",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repository Access Sync State",
                "verbose_name_plural": "Repository Access Sync States",
            },
        ),
        migrations.CreateModel(
            name="RepositoryAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")], max_length=10, verbose_name="provider"
                    ),
                ),
                ("uid", models.CharField(max_length=191, verbose_name="platform user ID")),
                ("username", models.CharField(blank=True, max_length=255, verbose_name="platform username")),
                ("repo_id", models.CharField(max_length=255, verbose_name="repository ID")),
                (
                    "access_level",
                    models.CharField(
                        choices=[("read", "Read"), ("write", "Write")], max_length=10, verbose_name="access level"
                    ),
                ),
                ("synced_at", models.DateTimeField(verbose_name="synced at")),
            ],
            options={
                "verbose_name": "Repository Access",
                "verbose_name_plural": "Repository Accesses",
                "indexes": [
                    models.Index(fields=["provider", "uid"], name="codebase_re_provide_29893e_idx"),
                    models.Index(fields=["provider", "repo_id"], name="codebase_re_provide_918738_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "uid", "repo_id"), name="repo_access_unique")
                ],
            },
        ),
    ]
