# Generated by Django 5.1.1 on 2024-10-09 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("codebase", "0001_initial")]

    operations = [
        migrations.RenameField(model_name="codebasenamespace", old_name="tracking_branch", new_name="tracking_ref")
    ]
