# Generated by Django 6.0.6 on 2026-07-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("codebase", "0002_repositoryaccesssyncstate_repositoryaccess")]

    operations = [
        migrations.CreateModel(
            name="RepositoryCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")], max_length=10, verbose_name="provider"
                    ),
                ),
                ("slug", models.CharField(max_length=255, verbose_name="repository slug")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="name")),
                ("default_branch", models.CharField(blank=True, max_length=255, verbose_name="default branch")),
                ("html_url", models.CharField(blank=True, max_length=512, verbose_name="HTML URL")),
                ("topics", models.JSONField(blank=True, default=list, verbose_name="topics")),
                ("synced_at", models.DateTimeField(verbose_name="synced at")),
            ],
            options={
                "verbose_name": "Repository Catalog",
                "verbose_name_plural": "Repository Catalog",
                "constraints": [models.UniqueConstraint(fields=("provider", "slug"), name="repo_catalog_unique")],
            },
        )
    ]
