# Generated by Django 5.1.2 on 2024-11-02 23:58

from django.db import migrations

from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [("codebase", "0002_rename_tracking_branch_codebasenamespace_tracking_ref")]

    operations = [VectorExtension()]
