# Generated by Django 6.1.1 on 2026-10-03 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("codebase", "0003_repository_catalog"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="CrossProjectAccessRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="occurred at")),
                ("thread_id", models.CharField(blank=True, db_index=True, max_length=255, verbose_name="thread ID")),
                (
                    "acting_user_label",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="acting user"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")], max_length=10, verbose_name="provider"
                    ),
                ),
                ("target_repo_id", models.CharField(max_length=255, verbose_name="target repository ID")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("denied_no_access", "Denied — no access"),
                            ("denied_no_credential", "Denied — no usable credential"),
                            ("denied_disabled", "Denied — capability disabled"),
                            ("denied_policy", "Denied — not permitted cross-project"),
                            ("error", "Error"),
                        ],
                        max_length=24,
                        verbose_name="outcome",
                    ),
                ),
                (
                    "acting_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_project_access_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cross-Project Access Record",
                "verbose_name_plural": "Cross-Project Access Records",
                "indexes": [models.Index(fields=["outcome", "occurred_at"], name="codebase_cr_outcome_906323_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("outcome", ""), _negated=True),
                        name="cross_project_access_record_outcome_required",
                    )
                ],
            },
        )
    ]
