# Generated by Django 5.1.4 on 2025-01-12 21:26

from django.db import migrations

import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [("codebase", "0004_codebasedocument")]

    operations = [
        migrations.AddField(
            model_name="codebasedocument",
            name="source_vector",
            field=pgvector.django.vector.VectorField(dimensions=1536),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="codebasedocument",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["source_vector"],
                m=16,
                name="source_hnsw_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
