# Generated by Django 5.1.4 on 2025-01-12 21:26

from django.db import migrations

import pgvector.django.indexes
import pgvector.django.vector

from codebase.search_engines.semantic import embeddings_function


def update_source_vector(apps, schema_editor):
    CodebaseDocument = apps.get_model("codebase", "CodebaseDocument")
    documents = CodebaseDocument.objects.all()
    embeddings = embeddings_function()
    source_vectors = embeddings.embed_documents([document.source for document in documents])
    for document, source_vector in zip(documents, source_vectors, strict=True):
        document.source_vector = source_vector
        document.save(update_fields=["source_vector"])


class Migration(migrations.Migration):
    dependencies = [("codebase", "0004_codebasedocument")]

    operations = [
        migrations.AddField(
            model_name="codebasedocument",
            name="source_vector",
            field=pgvector.django.vector.VectorField(null=True, dimensions=1536),
            preserve_default=False,
        ),
        migrations.RunPython(update_source_vector, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="codebasedocument",
            name="source_vector",
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AddIndex(
            model_name="codebasedocument",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["source_vector"],
                m=16,
                name="source_hnsw_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
