# Generated by Django 6.1 on 2026-09-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("codebase", "0004_crossprojectaccessrecord")]

    operations = [
        migrations.AlterField(
            model_name="crossprojectaccessrecord",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("allowed", "Allowed"),
                    ("denied_no_access", "Denied — no access"),
                    ("denied_no_credential", "Denied — no usable credential"),
                    ("denied_disabled", "Denied — capability disabled"),
                    ("denied_policy", "Denied — not permitted cross-project"),
                    ("error", "Error"),
                ],
                max_length=24,
                verbose_name="outcome",
            ),
        )
    ]
