# Generated by Django 6.1 on 2026-09-04 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codebase", "0005_alter_crossprojectaccessrecord_outcome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="crossprojectaccessrecord", name="identity_kind"),
        migrations.AddField(
            model_name="crossprojectaccessrecord",
            name="acting_user_label",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="acting user"),
        ),
        migrations.AddConstraint(
            model_name="crossprojectaccessrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("outcome", ""), _negated=True), name="cross_project_access_record_outcome_required"
            ),
        ),
    ]
