# Generated by Django 5.1.4 on 2025-01-19 02:34

from django.db import migrations, models

import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [("codebase", "0005_codebasedocument_source_vector_and_more")]

    operations = [
        migrations.AlterField(
            model_name="codebasedocument",
            name="page_content_vector",
            field=pgvector.django.vector.VectorField(dimensions=2000),
        ),
        migrations.AlterField(
            model_name="codebasedocument",
            name="source_vector",
            field=pgvector.django.vector.VectorField(dimensions=2000),
        ),
        migrations.AddIndex(
            model_name="codebasedocument", index=models.Index(models.F("metadata__ref"), name="metadata__ref_idx")
        ),
    ]
