# Generated by Django 5.1.5 on 2025-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("codebase", "0006_alter_codebasedocument_page_content_vector_and_more")]

    operations = [
        migrations.RemoveIndex(model_name="codebasedocument", name="source_hnsw_index"),
        migrations.RemoveIndex(model_name="codebasedocument", name="metadata__ref_idx"),
        migrations.RemoveField(model_name="codebasedocument", name="source_vector"),
        migrations.AddField(
            model_name="codebasedocument", name="is_default_branch", field=models.BooleanField(default=False)
        ),
    ]
