# Generated by Django 5.1.7 on 2025-03-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("codebase", "0008_auto_20250206_1900")]

    operations = [
        migrations.AddField(model_name="codebasedocument", name="description", field=models.TextField(blank=True))
    ]
