# Generated by Django 5.2 on 2025-04-08 22:21

from django.db import migrations

import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [("codebase", "0009_codebasedocument_description")]

    operations = [
        migrations.AlterField(
            model_name="codebasedocument", name="page_content_vector", field=pgvector.django.vector.VectorField()
        )
    ]
