# Generated by Django 5.2.1 on 2025-05-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("codebase", "0010_alter_codebasedocument_page_content_vector")]

    operations = [
        migrations.AddField(
            model_name="repositoryinfo", name="default_branch", field=models.CharField(blank=True, max_length=128)
        )
    ]
