sandbox:
  # Use the base image with uv installed
  base_image: "ghcr.io/astral-sh/uv:python3.14-bookworm"

  # Fix linting and format the code with ruff and pyproject-fmt
  format_code:
    - "uv sync --locked --only-group=dev"
    - "uv run --only-group=dev ruff check . --fix"
    - "uv run --only-group=dev ruff format ."
    - "uv run --only-group=dev pyproject-fmt pyproject.toml"
