# Generated by Django 6.0.4 on 2026-04-23 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                ("thread_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("repo_id", models.CharField(max_length=255, verbose_name="repository")),
                ("ref", models.CharField(blank=True, default="", max_length=255, verbose_name="ref")),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("active_run_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_active_at"],
                "indexes": [models.Index(fields=["user", "-last_active_at"], name="chat_chatth_user_id_abfd75_idx")],
            },
        )
    ]
