# Generated by Django 6.0.4 on 2026-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("chat", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="cache_read_tokens",
            field=models.PositiveBigIntegerField(default=0, verbose_name="cache read tokens"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="cache_write_tokens",
            field=models.PositiveBigIntegerField(default=0, verbose_name="cache write tokens"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="cost_priced",
            field=models.BooleanField(default=True, verbose_name="cost priced"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="cost_usd",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True, verbose_name="cost (USD)"
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="input_tokens",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="input tokens"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="last_input_tokens",
            field=models.PositiveIntegerField(default=0, verbose_name="last input tokens"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="last_model_name",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="last model name"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="output_tokens",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="output tokens"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="total_tokens",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="total tokens"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="usage_by_model",
            field=models.JSONField(blank=True, null=True, verbose_name="usage by model"),
        ),
    ]
