# Generated by Django 6.0.5 on 2026-05-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("chat", "0002_chatthread_sandbox_environment")]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="agent_model",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="agent model"),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="agent_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[("minimal", "Minimal"), ("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="",
                max_length=20,
                verbose_name="agent thinking level",
            ),
        ),
    ]
