# Generated by Django 6.0.6 on 2026-07-07 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatthread_agent_override_fields"),
        # Data was already copied to sessions.Session before we drop the source table.
        # Note: sessions app is registered under the label "agent_sessions".
        ("agent_sessions", "0002_backfill_from_activity_and_chat"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="chatthread", name="chat_chatth_user_id_abfd75_idx"),
        migrations.RemoveConstraint(model_name="chatthread", name="chat_active_run_id_nonempty"),
        migrations.DeleteModel(name="ChatThread"),
    ]
