# Django stuff:
*.log

# PyBuilder
target/

# local settings
venv/
data/
.tox/

.editorconfig
.gitignore
CHANGELOG.md
README.md

Dockerfile
docker-compose.yml
docker/local

*/static/node_modules
*/static/bundles/*.map
