#!/bin/sh

set -eu pipefail

django-admin migrate --noinput

exec uvicorn --host ${UVICORN_HOST:-0.0.0.0} --port ${UVICORN_PORT:-8000} --lifespan off --app-dir "/home/daiv/app" "daiv.asgi:application"
