#!/bin/sh

set -eu

django-admin migrate --noinput
django-admin setup_default_site
django-admin setup_checkpoint_saver
django-admin collectstatic --noinput

exec uvicorn --host ${UVICORN_HOST:-0.0.0.0} --port ${UVICORN_PORT:-8000} --lifespan on --app-dir "/home/daiv/app" "daiv.asgi:application"
