# Generated by Django 6.0.3 on 2026-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "agent_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary model for agent tasks.",
                        max_length=255,
                        null=True,
                        verbose_name="model",
                    ),
                ),
                (
                    "agent_fallback_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Fallback model when the primary model fails.",
                        max_length=255,
                        null=True,
                        verbose_name="fallback model",
                    ),
                ),
                (
                    "agent_thinking_level",
                    models.CharField(
                        blank=True,
                        choices=[("minimal", "Minimal"), ("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        help_text="Extended thinking depth for agent tasks. Leave empty to disable thinking.",
                        max_length=10,
                        null=True,
                        verbose_name="thinking level",
                    ),
                ),
                (
                    "agent_max_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Model for tasks when the daiv-max label is present.",
                        max_length=255,
                        null=True,
                        verbose_name="max model",
                    ),
                ),
                (
                    "agent_max_thinking_level",
                    models.CharField(
                        blank=True,
                        choices=[("minimal", "Minimal"), ("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        help_text="Thinking depth for daiv-max tasks. Leave empty to disable thinking.",
                        max_length=10,
                        null=True,
                        verbose_name="max thinking level",
                    ),
                ),
                (
                    "agent_explore_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Fast model for the explore subagent.",
                        max_length=255,
                        null=True,
                        verbose_name="explore model",
                    ),
                ),
                (
                    "agent_recursion_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum recursion depth for agent loops.",
                        null=True,
                        verbose_name="recursion limit",
                    ),
                ),
                (
                    "diff_to_metadata_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Model for generating commit messages and PR descriptions from diffs.",
                        max_length=255,
                        null=True,
                        verbose_name="model",
                    ),
                ),
                (
                    "diff_to_metadata_fallback_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Fallback model used when the primary fails.",
                        max_length=255,
                        null=True,
                        verbose_name="fallback model",
                    ),
                ),
                (
                    "web_search_enabled",
                    models.BooleanField(
                        help_text="Enable or disable the web search tool.", null=True, verbose_name="web search enabled"
                    ),
                ),
                (
                    "web_search_max_results",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of results returned from web search.",
                        null=True,
                        verbose_name="web search max results",
                    ),
                ),
                (
                    "web_search_engine",
                    models.CharField(
                        blank=True,
                        choices=[("duckduckgo", "DuckDuckGo"), ("tavily", "Tavily")],
                        help_text="Search engine to use. Tavily requires an API key.",
                        max_length=20,
                        null=True,
                        verbose_name="web search engine",
                    ),
                ),
                (
                    "web_fetch_enabled",
                    models.BooleanField(
                        help_text="Enable or disable the web fetch tool.", null=True, verbose_name="web fetch enabled"
                    ),
                ),
                (
                    "web_fetch_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Model used to process fetched page content.",
                        max_length=255,
                        null=True,
                        verbose_name="web fetch model",
                    ),
                ),
                (
                    "web_fetch_cache_ttl_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cache time-to-live for fetched pages, in seconds.",
                        null=True,
                        verbose_name="web fetch cache TTL",
                    ),
                ),
                (
                    "web_fetch_timeout_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="HTTP timeout for web fetch requests, in seconds.",
                        null=True,
                        verbose_name="web fetch timeout",
                    ),
                ),
                (
                    "web_fetch_max_content_chars",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum page content size (in characters) to analyze in one pass.",
                        null=True,
                        verbose_name="web fetch max content",
                    ),
                ),
                (
                    "sandbox_timeout",
                    models.FloatField(
                        blank=True,
                        help_text="Timeout for sandbox requests, in seconds.",
                        null=True,
                        verbose_name="sandbox timeout",
                    ),
                ),
                (
                    "sandbox_base_image",
                    models.CharField(
                        blank=True,
                        help_text="Default Docker base image for sandbox sessions.",
                        max_length=255,
                        null=True,
                        verbose_name="sandbox base image",
                    ),
                ),
                (
                    "sandbox_ephemeral",
                    models.BooleanField(
                        help_text="Whether sandbox sessions are ephemeral by default.",
                        null=True,
                        verbose_name="sandbox ephemeral",
                    ),
                ),
                (
                    "sandbox_network_enabled",
                    models.BooleanField(
                        help_text="Whether to enable network access in sandbox sessions by default.",
                        null=True,
                        verbose_name="sandbox network enabled",
                    ),
                ),
                (
                    "sandbox_cpu",
                    models.FloatField(
                        blank=True,
                        help_text="CPUs to allocate to sandbox sessions by default. Leave empty for no limit.",
                        null=True,
                        verbose_name="sandbox CPU",
                    ),
                ),
                (
                    "sandbox_memory",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Memory limit in bytes to allocate to sandbox sessions by default. Leave empty for no limit.",
                        null=True,
                        verbose_name="sandbox memory",
                    ),
                ),
                (
                    "suggest_context_file_enabled",
                    models.BooleanField(
                        help_text="Suggest creating a context file (e.g. AGENTS.md) on new merge requests.",
                        null=True,
                        verbose_name="suggest context file",
                    ),
                ),
                (
                    "jobs_throttle_rate",
                    models.CharField(
                        blank=True,
                        help_text="Rate limit for job submissions per authenticated user (e.g. '20/hour').",
                        max_length=50,
                        null=True,
                        verbose_name="jobs throttle rate",
                    ),
                ),
                (
                    "openrouter_api_base",
                    models.CharField(
                        blank=True,
                        help_text="Base URL for the OpenRouter API.",
                        max_length=255,
                        null=True,
                        verbose_name="OpenRouter API base URL",
                    ),
                ),
                ("_anthropic_api_key_encrypted", models.TextField(blank=True, editable=False, null=True)),
                ("_openai_api_key_encrypted", models.TextField(blank=True, editable=False, null=True)),
                ("_google_api_key_encrypted", models.TextField(blank=True, editable=False, null=True)),
                ("_openrouter_api_key_encrypted", models.TextField(blank=True, editable=False, null=True)),
                ("_web_search_api_key_encrypted", models.TextField(blank=True, editable=False, null=True)),
                ("_sandbox_api_key_encrypted", models.TextField(blank=True, editable=False, null=True)),
            ],
            options={"verbose_name": "site configuration", "verbose_name_plural": "site configuration"},
        )
    ]
