# Generated by Django 6.0.3 on 2026-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0001_site_configuration")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="agent_explore_fallback_model_name",
            field=models.CharField(
                blank=True,
                help_text="Fallback model when the explore model fails.",
                max_length=255,
                null=True,
                verbose_name="explore fallback model",
            ),
        )
    ]
