# Generated by Django 6.0.3 on 2026-04-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0001_site_configuration")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="openrouter_api_base",
            field=models.CharField(
                blank=True,
                help_text="Base URL for the OpenRouter API.",
                max_length=255,
                null=True,
                verbose_name="OpenRouter API base URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="sandbox_cpu",
            field=models.FloatField(
                blank=True,
                help_text="CPUs to allocate to sandbox sessions by default.",
                null=True,
                verbose_name="sandbox CPU",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="sandbox_memory",
            field=models.BigIntegerField(
                blank=True,
                help_text="Memory limit in bytes to allocate to sandbox sessions by default.",
                null=True,
                verbose_name="sandbox memory",
            ),
        ),
    ]
