# Generated by Django 6.0.4 on 2026-04-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0002_siteconfiguration_agent_explore_fallback_model_name")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="_auth_client_secret_encrypted",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="auth_client_id",
            field=models.CharField(
                blank=True,
                help_text="OAuth application client ID for the configured Git platform.",
                max_length=255,
                null=True,
                verbose_name="OAuth client ID",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="auth_gitlab_server_url",
            field=models.CharField(
                blank=True,
                help_text="Server-to-server URL for GitLab API calls (token exchange, profile fetch) in Docker-internal networks. Leave empty to use the GitLab URL.",
                max_length=255,
                null=True,
                verbose_name="GitLab server URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="auth_gitlab_url",
            field=models.CharField(
                blank=True,
                help_text="Browser-facing URL of your GitLab instance.",
                max_length=255,
                null=True,
                verbose_name="GitLab URL",
            ),
        ),
    ]
