# Generated by Django 6.0.4 on 2026-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0003_add_auth_fields")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="auth_signup_open",
            field=models.BooleanField(
                help_text="Allow anyone who authenticates via the configured Git platform to create an account. When disabled, only users pre-created by an admin can sign in.",
                null=True,
                verbose_name="open social signup",
            ),
        )
    ]
