# Generated by Django 6.0.4 on 2026-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0004_siteconfiguration_auth_signup_open")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="_rocketchat_auth_token_encrypted",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="rocketchat_url",
            field=models.CharField(
                blank=True,
                help_text="Base URL of your Rocket Chat instance (e.g. https://rc.example.com).",
                max_length=255,
                null=True,
                verbose_name="Rocket Chat URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="rocketchat_user_id",
            field=models.CharField(
                blank=True,
                help_text="The bot user's _id, sent as the X-User-Id header.",
                max_length=64,
                null=True,
                verbose_name="Rocket Chat bot user ID",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="rocketchat_enabled",
            field=models.BooleanField(
                help_text="Offer Rocket Chat as a notification channel for users.",
                null=True,
                verbose_name="enable Rocket Chat",
            ),
        ),
    ]
