# Generated by Django 6.0.4 on 2026-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0005_rocketchat_fields")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="titling_model_name",
            field=models.CharField(
                blank=True,
                help_text="Model for generating chat thread and activity titles from prompts.",
                max_length=255,
                null=True,
                verbose_name="model",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="titling_fallback_model_name",
            field=models.CharField(
                blank=True,
                help_text="Fallback model used when the primary fails.",
                max_length=255,
                null=True,
                verbose_name="fallback model",
            ),
        ),
    ]
