# Generated by Django 6.0.4 on 2026-05-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0006_titling_models")]

    operations = [
        migrations.CreateModel(
            name="WebFetchAuthHeader",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=255, verbose_name="domain")),
                ("header_name", models.CharField(max_length=255, verbose_name="header name")),
                ("_header_value_encrypted", models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                "verbose_name": "web fetch auth header",
                "verbose_name_plural": "web fetch auth headers",
                "ordering": ("domain", "header_name"),
                "constraints": [
                    models.UniqueConstraint(fields=("domain", "header_name"), name="unique_web_fetch_auth_header")
                ],
            },
        )
    ]
