# Generated by Django 6.0.4 on 2026-05-11 16:06

import os

from django.db import migrations, models

SEED_ROWS = [
    {
        "slug": "anthropic",
        "display_name": "Anthropic",
        "provider_type": "anthropic",
        "base_url": "",
        "sort_order": 10,
        "env_var": "ANTHROPIC_API_KEY",
        "db_column": "_anthropic_api_key_encrypted",
    },
    {
        "slug": "openai",
        "display_name": "OpenAI",
        "provider_type": "openai",
        "base_url": "",
        "sort_order": 20,
        "env_var": "OPENAI_API_KEY",
        "db_column": "_openai_api_key_encrypted",
    },
    {
        "slug": "google_genai",
        "display_name": "Google Gemini",
        "provider_type": "google_genai",
        "base_url": "",
        "sort_order": 30,
        "env_var": "GOOGLE_API_KEY",
        "db_column": "_google_api_key_encrypted",
    },
    {
        "slug": "openrouter",
        "display_name": "OpenRouter",
        "provider_type": "openrouter",
        "base_url": "https://openrouter.ai/api/v1",
        "sort_order": 40,
        "env_var": "OPENROUTER_API_KEY",
        "db_column": "_openrouter_api_key_encrypted",
    },
]


def seed_providers(apps, schema_editor):
    import warnings

    from cryptography.fernet import InvalidToken

    from core.encryption import decrypt_value, encrypt_value

    Provider = apps.get_model("core", "Provider")
    SiteConfiguration = apps.get_model("core", "SiteConfiguration")
    cfg = SiteConfiguration.objects.filter(pk=1).first()

    for seed in SEED_ROWS:
        key_plaintext: str | None = None
        decrypt_failed = False
        if cfg is not None:
            encrypted = getattr(cfg, seed["db_column"], None)
            if encrypted:
                try:
                    key_plaintext = decrypt_value(encrypted)
                except InvalidToken:
                    decrypt_failed = True
                    key_plaintext = None
        if not key_plaintext:
            env_value = os.environ.get(seed["env_var"])
            if env_value:
                key_plaintext = env_value
            elif decrypt_failed:
                # Legacy ciphertext is about to be dropped by this same migration; warn loudly
                # so the operator notices that a previously-working key is gone — usually a
                # rotated DAIV_ENCRYPTION_KEY since the data was encrypted.
                warnings.warn(
                    f"Could not decrypt legacy {seed['db_column']} for provider "
                    f"'{seed['slug']}' (DAIV_ENCRYPTION_KEY may have rotated). Set the key "
                    f"via the configuration UI or {seed['env_var']} to re-enable.",
                    stacklevel=2,
                )

        base_url = seed["base_url"]
        if seed["slug"] == "openrouter" and cfg is not None and getattr(cfg, "openrouter_api_base", None):
            base_url = cfg.openrouter_api_base

        # Real OpenAI fully supports the Responses API, so the locked ``openai`` seed
        # row keeps the pre-flag behavior. Other providers (Anthropic/Google/OpenRouter)
        # ignore this flag, and custom rows default to ``False`` because most
        # OpenAI-compatible servers only implement ``/v1/chat/completions``.
        Provider.objects.update_or_create(
            slug=seed["slug"],
            defaults={
                "display_name": seed["display_name"],
                "provider_type": seed["provider_type"],
                "base_url": base_url,
                "_api_key_encrypted": encrypt_value(key_plaintext) if key_plaintext else None,
                "extra_headers": {},
                "is_enabled": bool(key_plaintext),
                "use_responses_api": seed["slug"] == "openai",
                "verify_ssl": True,
                "is_locked": True,
                "sort_order": seed["sort_order"],
            },
        )


def unseed_providers(apps, schema_editor):
    Provider = apps.get_model("core", "Provider")
    Provider.objects.filter(slug__in=[s["slug"] for s in SEED_ROWS], is_locked=True).delete()


class Migration(migrations.Migration):
    dependencies = [("core", "0007_webfetchauthheader")]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=32, unique=True, verbose_name="slug")),
                ("display_name", models.CharField(max_length=64, verbose_name="display name")),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google_genai", "Google Gemini"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=32,
                        verbose_name="provider type",
                    ),
                ),
                ("base_url", models.URLField(blank=True, verbose_name="base URL")),
                ("_api_key_encrypted", models.TextField(blank=True, editable=False, null=True)),
                ("extra_headers", models.JSONField(blank=True, default=dict, verbose_name="extra headers")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "use_responses_api",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Only honored for OpenAI-typed providers. Enable for servers that expose"
                            " /v1/responses (real OpenAI, some hosted gateways). Disable for"
                            " /v1/chat/completions-only servers (vLLM, llama.cpp, most LiteLLM setups)."
                        ),
                        verbose_name="use Responses API",
                    ),
                ),
                (
                    "verify_ssl",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Disable only for self-hosted endpoints behind an internal/self-signed CA."
                            " Skipping verification exposes the connection to MITM attacks; prefer mounting"
                            " the internal CA into the daiv containers when possible."
                        ),
                        verbose_name="verify TLS certificates",
                    ),
                ),
                ("is_locked", models.BooleanField(default=False, editable=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "provider",
                "verbose_name_plural": "providers",
                "ordering": ("sort_order", "slug"),
            },
        ),
        migrations.RunPython(seed_providers, unseed_providers),
        migrations.RemoveField(model_name="siteconfiguration", name="_anthropic_api_key_encrypted"),
        migrations.RemoveField(model_name="siteconfiguration", name="_google_api_key_encrypted"),
        migrations.RemoveField(model_name="siteconfiguration", name="_openai_api_key_encrypted"),
        migrations.RemoveField(model_name="siteconfiguration", name="_openrouter_api_key_encrypted"),
        migrations.RemoveField(model_name="siteconfiguration", name="openrouter_api_base"),
    ]
