# Generated by Django 6.0.5 on 2026-05-18 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("core", "0008_provider")]

    operations = [
        migrations.RemoveField(model_name="siteconfiguration", name="sandbox_base_image"),
        migrations.RemoveField(model_name="siteconfiguration", name="sandbox_cpu"),
        migrations.RemoveField(model_name="siteconfiguration", name="sandbox_ephemeral"),
        migrations.RemoveField(model_name="siteconfiguration", name="sandbox_memory"),
        migrations.RemoveField(model_name="siteconfiguration", name="sandbox_network_enabled"),
    ]
