# Generated by Django 6.0.4 on 2026-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0009_drop_sandbox_overrides")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="agent_fallback_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[("minimal", "Minimal"), ("low", "Low"), ("medium", "Medium"), ("high", "High")],
                help_text="Thinking depth applied to the fallback model. Independent of the primary thinking level.",
                max_length=10,
                null=True,
                verbose_name="fallback thinking level",
            ),
        )
    ]
