# Generated by Django 6.0.6 on 2026-06-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0010_siteconfiguration_agent_fallback_thinking_level")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_enabled",
            field=models.BooleanField(
                help_text=(
                    "Capture learnings from finished runs, consolidate them, and inject them into future runs."
                    " A per-repository .daiv.yml flag can still opt an individual repository out."
                ),
                null=True,
                verbose_name="memory enabled",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_extraction_model_name",
            field=models.CharField(
                blank=True,
                help_text="Cheap model that extracts candidate observations from each finished run's transcript.",
                max_length=255,
                null=True,
                verbose_name="extraction model",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_extraction_fallback_model_name",
            field=models.CharField(
                blank=True,
                help_text="Fallback model when the extraction model fails.",
                max_length=255,
                null=True,
                verbose_name="extraction fallback model",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_consolidation_model_name",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Model that rewrites the memory document. Leave empty to reuse the repository's agent model."
                ),
                max_length=255,
                null=True,
                verbose_name="consolidation model",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_consolidation_min_pending",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Consolidate once at least this many pending observations have accumulated "
                    "(subject to the consolidation interval below)."
                ),
                null=True,
                verbose_name="consolidation threshold",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_consolidation_min_interval_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum hours between consolidations for the same repository.",
                null=True,
                verbose_name="consolidation interval (hours)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_max_lines",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Hard cap on the consolidated memory document length, in lines.",
                null=True,
                verbose_name="memory max lines",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_max_bytes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Hard cap on the consolidated memory document size, in bytes.",
                null=True,
                verbose_name="memory max bytes",
            ),
        ),
    ]
