# Generated by Django 6.0.6 on 2026-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0011_siteconfiguration_memory_fields")]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="agent_fallback_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimal", "Minimal"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("xhigh", "Extra high"),
                ],
                help_text="Thinking depth applied to the fallback model. Independent of the primary thinking level.",
                max_length=10,
                null=True,
                verbose_name="fallback thinking level",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="agent_max_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimal", "Minimal"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("xhigh", "Extra high"),
                ],
                help_text="Thinking depth for daiv-max tasks. Leave empty to disable thinking.",
                max_length=10,
                null=True,
                verbose_name="max thinking level",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="agent_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimal", "Minimal"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("xhigh", "Extra high"),
                ],
                help_text="Extended thinking depth for agent tasks. Leave empty to disable thinking.",
                max_length=10,
                null=True,
                verbose_name="thinking level",
            ),
        ),
    ]
