# Generated by Django 6.0.7 on 2026-07-13 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0012_alter_siteconfiguration_agent_fallback_thinking_level_and_more")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="model_max_retries",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Retries for a failed LLM API call before the error propagates. Applies to every provider.",
                null=True,
                verbose_name="model max retries",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="model_request_timeout_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Per-request timeout for LLM API calls, in seconds. Applies to every provider.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="model request timeout",
            ),
        ),
    ]
