# Generated by Django 6.0.7 on 2026-07-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0012_alter_siteconfiguration_agent_fallback_thinking_level_and_more")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="run_classifier_fallback_model_name",
            field=models.CharField(
                blank=True,
                help_text="Fallback model when the classifier model fails.",
                max_length=255,
                null=True,
                verbose_name="classifier fallback model",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="run_classifier_model_name",
            field=models.CharField(
                blank=True,
                help_text="Model that classifies each finished scheduled run's report into an envelope.",
                max_length=255,
                null=True,
                verbose_name="classifier model",
            ),
        ),
    ]
