# Generated by Django 6.0.7 on 2026-08-04 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0013_siteconfiguration_run_classifier_fallback_model_name_and_more")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="memory_consolidation_max_pending_age_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Consolidate a repository that is still below the threshold above once its oldest pending observation reaches this age, so low-volume repositories still form memory.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="consolidation flush age (days)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="memory_max_bytes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cap on the memory document size in bytes; entries beyond it are evicted.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="memory max bytes",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="memory_max_lines",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cap on the memory document length in lines; entries beyond it are evicted.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="memory max lines",
            ),
        ),
    ]
