# Generated by Django 6.0.7 on 2026-08-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0014_siteconfiguration_memory_flush_age_and_budget_bounds")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="session_link_enabled",
            field=models.BooleanField(
                help_text="Link back to the DAIV sessions that produced the changes, from the descriptions of merge requests DAIV opens and from a DAIV-Session trailer on every commit. Disable to keep the DAIV URL off the git platform.",
                null=True,
                verbose_name="link sessions from merge requests",
            ),
        )
    ]
