# Generated by Django 6.0.7 on 2026-08-25 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0015_siteconfiguration_session_link_enabled")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="pipeline_watch_enabled",
            field=models.BooleanField(
                blank=True,
                help_text="Watch CI on merge requests DAIV publishes and try to fix failures.",
                null=True,
                verbose_name="pipeline watch enabled",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="pipeline_watch_max_attempts",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How many fix attempts to spend on one merge request before handing back.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="pipeline watch max attempts",
            ),
        ),
    ]
