# Generated by Django 6.1 on 2026-09-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0016_siteconfiguration_pipeline_watch")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="cross_project_access_enabled",
            field=models.BooleanField(
                help_text="Allow the git platform tools to target projects other than the attached one, acting as the person who requested the run. Off by default: enabling it widens what the agent can reach.",
                null=True,
                verbose_name="cross-project access enabled",
            ),
        )
    ]
