import asyncio
import json
import logging
import uuid as uuid_mod
from typing import TYPE_CHECKING, Annotated

from activity.models import TriggerType
from activity.services import MAX_REPOS_PER_BATCH, RepoTarget, asubmit_batch_runs
from django_tasks_db.models import DBTaskResult
from jobs.tasks import run_job_task
from mcp.server.auth.settings import AuthSettings
from mcp.server.fastmcp import FastMCP
from mcp.server.transport_security import TransportSecuritySettings
from notifications.choices import NotifyOn  # noqa: TC002 - required at runtime for MCP tool schema
from pydantic import BaseModel, Field
from sandbox_envs.models import SandboxEnvironment, Scope
from sandbox_envs.services import looks_like_uuid, resolve_env_for_user

from automation.agent.results import parse_agent_result
from codebase.clients import RepoClient
from core.conf import settings as core_settings
from mcp_server.auth import DjangoOAuthTokenVerifier, get_current_user

if TYPE_CHECKING:
    from codebase.base import Repository

logger = logging.getLogger("daiv.mcp_server")

_external_url = str(core_settings.EXTERNAL_URL).rstrip("/")

mcp = FastMCP(
    name="DAIV",
    instructions="""\
DAIV is an autonomous coding agent that operates on Git repositories (GitLab and GitHub). \
It reads, writes, and edits files, runs shell commands in a sandbox, and debugs CI/CD pipelines.

**Automatic post-job steps — do NOT ask for these in `prompt`.** When a job produces code \
changes, DAIV automatically commits, pushes, and ensures a merge/pull request exists. The \
branch name, commit message, and MR/PR title and description are generated by DAIV from \
the diff — do NOT supply them, and do NOT instruct the agent to "commit", "push", "create \
a branch", or "open a PR/MR". Such instructions waste tokens and can mislead the agent. \
The response includes `merge_request_url` when one was created or updated.

Use `list_repositories` to discover available repositories by name or topic. \
If the user already knows the `repo_id`, skip discovery and call `submit_job` directly.

Write specific prompts describing the intended change: include file paths, function names, \
or error messages. Vague requests produce poor results.

`ref` is the STARTING POINT the agent reads from (base branch or commit SHA), not a target \
branch name. Omit it to start from the repository default branch. If `ref` is a branch \
that already has an open MR/PR, DAIV pushes the new commit onto that same branch and \
updates the existing MR/PR — useful for fixing CI or in-review branch. \
Otherwise DAIV creates a new branch and opens a new MR/PR.

Jobs are rate-limited per user. Long-running jobs may exceed the 10-minute polling window; \
continue polling with `get_job_status` if the result is not yet available.\
""",
    stateless_http=True,
    transport_security=TransportSecuritySettings(enable_dns_rebinding_protection=False),
    auth=AuthSettings(issuer_url=_external_url, resource_server_url=f"{_external_url}/mcp", required_scopes=["mcp"]),
    token_verifier=DjangoOAuthTokenVerifier(),
)


TERMINAL_STATUSES = {"SUCCESSFUL", "FAILED"}
POLL_INTERVAL = 2.0
MAX_POLL_DURATION = 600.0  # 10 minutes


class RepoSubmitSpec(BaseModel):
    repo_id: str = Field(description='Repository identifier. "owner/repo" for GitHub or full project path for GitLab.')
    ref: str | None = Field(
        default=None, description="Git reference (branch name or commit SHA). None / empty string = default branch."
    )


@mcp.tool()
async def submit_job(
    repos: Annotated[
        list[RepoSubmitSpec], Field(min_length=1, max_length=20, description="1-20 repositories to run against.")
    ],
    prompt: Annotated[
        str,
        Field(
            description=(
                "Task instruction for the agent. Describe the intended change — do NOT ask the agent"
                " to commit, push, create a branch, or open a merge/pull request; those steps run"
                " automatically after the job, and DAIV generates the branch name, commit message,"
                " and MR/PR title/description itself. Be specific: include file paths, function"
                " names, or error messages. The same prompt runs independently against each repository."
            )
        ),
    ],
    use_max: Annotated[
        bool, Field(description="Use the max model configuration (more capable model with thinking set to high).")
    ] = False,
    notify_on: Annotated[
        NotifyOn | None,
        Field(
            description=(
                "When to receive notifications for each job. When omitted, falls back to the user's default preference."
            )
        ),
    ] = None,
    wait: Annotated[
        bool,
        Field(
            description=(
                "When true, blocks until every job in the batch completes (up to 10 minutes total)"
                " and returns each job's full result."
            )
        ),
    ] = False,
    environment: Annotated[
        str | None,
        Field(
            description=(
                "Optional sandbox environment to use for every job in this batch — pass the env"
                " name or UUID. Visible scopes are the caller's USER envs plus all GLOBAL envs."
                " Use ``list_environments`` to discover names. Omit to fall back to repo"
                " ``.daiv.yml`` and the GLOBAL default."
            )
        ),
    ] = None,
) -> str:
    """Submit a batch of agent jobs. Each repository runs as an independent job.

    Returns ``{batch_id, jobs: [{job_id, repo_id, ref}], failed: [...]}``. Each job runs
    independently; poll with ``get_job_status`` per job_id or pass ``wait=true``.
    """
    # FastMCP validates only at the protocol layer; direct calls bypass it.
    if not repos:
        return json.dumps({"error": "At least one repository is required."})
    if len(repos) > MAX_REPOS_PER_BATCH:
        return json.dumps({"error": f"At most {MAX_REPOS_PER_BATCH} repositories allowed per submission."})

    specs = [spec if isinstance(spec, RepoSubmitSpec) else RepoSubmitSpec(**spec) for spec in repos]

    mcp_user = None
    try:
        mcp_user = await get_current_user()
    except Exception:
        logger.exception("Failed to resolve current user for MCP submit_job")

    sandbox_environment_id: str | None = None
    if environment:
        try:
            env_row = await resolve_env_for_user(mcp_user, environment)
        except LookupError as err:
            return json.dumps({"error": str(err)})
        if env_row is not None:
            sandbox_environment_id = str(env_row.id)

    targets = [RepoTarget(repo_id=s.repo_id, ref=s.ref or "") for s in specs]
    result = await asubmit_batch_runs(
        user=mcp_user,
        prompt=prompt,
        repos=targets,
        use_max=use_max,
        notify_on=notify_on,
        trigger_type=TriggerType.MCP_JOB,
        sandbox_environment_id=sandbox_environment_id,
    )

    # Preserve the client-sent ref value (None vs "") by walking the specs and pairing each
    # non-failed one with the next activity in result.activities (same order as input).
    failed_keys = {(f.repo_id, f.ref) for f in result.failed}
    activities_iter = iter(result.activities)
    jobs: list[dict] = []
    job_ids: list[str] = []
    for spec in specs:
        if (spec.repo_id, spec.ref or "") in failed_keys:
            continue
        activity = next(activities_iter)
        jobs.append({"job_id": str(activity.task_result_id), "repo_id": spec.repo_id, "ref": spec.ref})
        job_ids.append(str(activity.task_result_id))

    failed_out = [{"repo_id": f.repo_id, "ref": f.ref, "error": f.error} for f in result.failed]

    logger.info("MCP batch submitted: batch_id=%s count=%d failures=%d", result.batch_id, len(jobs), len(failed_out))

    response: dict = {"batch_id": str(result.batch_id), "jobs": jobs, "failed": failed_out}
    if not wait:
        return json.dumps(response)

    return await _poll_batch_until_complete(str(result.batch_id), job_ids, response)


def _build_job_response_dict(db_result: DBTaskResult) -> dict:
    """Build a dict response from a DBTaskResult (shared by single + batch paths)."""
    error = "Job execution failed." if db_result.status == "FAILED" else None
    parsed = parse_agent_result(db_result.return_value)
    return {
        "job_id": str(db_result.id),
        "status": db_result.status,
        "result": parsed["response"] or None,
        "merge_request_url": parsed["merge_request_web_url"],
        "error": error,
        "created_at": db_result.enqueued_at.isoformat() if db_result.enqueued_at else None,
        "started_at": db_result.started_at.isoformat() if db_result.started_at else None,
        "finished_at": db_result.finished_at.isoformat() if db_result.finished_at else None,
    }


def _build_job_response(db_result: DBTaskResult) -> str:
    """Build a JSON response string from a DBTaskResult."""
    return json.dumps(_build_job_response_dict(db_result))


def _batch_response(batch_id: str, enqueue_response: dict, results_by_id: dict[str, DBTaskResult]) -> str:
    return json.dumps({
        "batch_id": batch_id,
        "jobs": enqueue_response["jobs"],
        "failed": enqueue_response["failed"],
        "statuses": [
            _build_job_response_dict(results_by_id[jid])
            if jid in results_by_id
            else {"job_id": jid, "status": "PENDING"}
            for jid in [j["job_id"] for j in enqueue_response["jobs"]]
        ],
    })


async def _poll_batch_until_complete(batch_id: str, job_ids: list[str], enqueue_response: dict) -> str:
    """Poll every job in the batch until terminal or the 10-minute budget is exhausted."""
    results_by_id: dict[str, DBTaskResult] = {}
    if not job_ids:
        return _batch_response(batch_id, enqueue_response, results_by_id)

    elapsed = 0.0
    outstanding = {uuid_mod.UUID(j) for j in job_ids}

    while elapsed < MAX_POLL_DURATION and outstanding:
        await asyncio.sleep(POLL_INTERVAL)
        elapsed += POLL_INTERVAL

        try:
            async for row in DBTaskResult.objects.filter(id__in=list(outstanding), task_path=run_job_task.module_path):
                if row.status in TERMINAL_STATUSES:
                    results_by_id[str(row.id)] = row
                    outstanding.discard(row.id)
        except Exception:
            logger.exception("Failed to poll batch_id=%s", batch_id)
            break

    return _batch_response(batch_id, enqueue_response, results_by_id)


async def _poll_job_until_complete(job_id: str) -> str:
    """Poll a job until it reaches a terminal status or the timeout is exceeded."""
    job_uuid = uuid_mod.UUID(job_id)
    elapsed = 0.0
    last_result: DBTaskResult | None = None

    while elapsed < MAX_POLL_DURATION:
        await asyncio.sleep(POLL_INTERVAL)
        elapsed += POLL_INTERVAL

        try:
            last_result = await DBTaskResult.objects.aget(id=job_uuid, task_path=run_job_task.module_path)
        except DBTaskResult.DoesNotExist:
            logger.debug("Job %s not yet available, retrying (%.0fs elapsed)", job_id, elapsed)
            continue
        except Exception:
            logger.exception("Failed to poll job status for job_id=%s", job_id)
            return json.dumps({"error": "Failed to retrieve job status. Please try again later.", "job_id": job_id})

        if last_result.status in TERMINAL_STATUSES:
            return _build_job_response(last_result)

    # Timeout — return current status so the caller isn't left without info
    if last_result is not None:
        logger.info(
            "Polling timeout for job_id=%s after %.0fs, returning current status: %s",
            job_id,
            elapsed,
            last_result.status,
        )
        return _build_job_response(last_result)

    logger.warning("Polling timeout for job_id=%s after %.0fs, job never appeared in database", job_id, elapsed)
    return json.dumps({
        "error": f"Job '{job_id}' was submitted but has not appeared yet after {int(MAX_POLL_DURATION)}s. "
        "The task queue may be backed up. Use get_job_status to check later.",
        "job_id": job_id,
    })


@mcp.tool()
async def get_job_status(
    job_id: Annotated[str, Field(description="The job ID returned by submit_job.")],
    wait: Annotated[
        bool,
        Field(
            description=(
                "When true, blocks until the job completes (up to 10 minutes) instead of returning immediately."
            )
        ),
    ] = False,
) -> str:
    """Get the status and result of a previously submitted job. Status is one of: READY, RUNNING, SUCCESSFUL, FAILED."""
    try:
        job_uuid = uuid_mod.UUID(job_id)
    except ValueError:
        return json.dumps({"error": "Invalid job_id format."})

    try:
        db_result = await DBTaskResult.objects.aget(id=job_uuid, task_path=run_job_task.module_path)
    except DBTaskResult.DoesNotExist:
        if wait:
            return await _poll_job_until_complete(job_id)
        return json.dumps({"error": "Job not found."})
    except Exception:
        logger.exception("Failed to retrieve job status for job_id=%s", job_id)
        return json.dumps({"error": "Failed to retrieve job status. Please try again later."})

    if wait and db_result.status not in TERMINAL_STATUSES:
        return await _poll_job_until_complete(job_id)

    return _build_job_response(db_result)


MAX_REPOSITORIES = 40


def _serialize_repositories(repos: list[Repository]) -> list[dict]:
    """Convert a list of Repository objects to serializable dicts."""
    return [repo.model_dump(include={"slug", "name", "html_url", "default_branch", "topics"}) for repo in repos]


@mcp.tool()
async def list_repositories(
    search: Annotated[str | None, Field(description="Filter repositories by name (partial match).")] = None,
    topics: Annotated[list[str] | None, Field(description="Filter repositories by topic tags.")] = None,
) -> str:
    """
    List repositories accessible to DAIV, optionally filtered by name or topic.
    Results may be truncated; use search or topics to narrow down.
    """
    # Fetch one extra to detect truncation without loading everything
    fetch_limit = MAX_REPOSITORIES + 1
    try:
        client = RepoClient.create_instance()
        repos = await asyncio.to_thread(client.list_repositories, search=search, topics=topics, limit=fetch_limit)
    except Exception:
        logger.exception("Failed to list repositories")
        return json.dumps({"error": "Failed to list repositories. Please try again later."})

    truncated = len(repos) > MAX_REPOSITORIES
    result: dict = {"repositories": _serialize_repositories(repos[:MAX_REPOSITORIES])}
    if truncated:
        result["warning"] = (
            f"Only the first {MAX_REPOSITORIES} repositories are shown. "
            "There are more results available. Ask the user to provide a search term or topic to narrow down."
        )
    return json.dumps(result)


@mcp.tool()
async def list_environments() -> list[dict]:
    """List sandbox environments visible to the caller — their own USER envs plus all GLOBAL envs.

    Use the returned ``name`` (or ``id``) as the ``environment`` argument to ``submit_job``.
    Secret env-var values are not included; call ``get_environment`` for full details.
    """
    from django.db.models import Q

    user = await get_current_user()
    qs = SandboxEnvironment.objects.filter(Q(scope=Scope.USER, user=user) | Q(scope=Scope.GLOBAL)).order_by(
        "scope", "name"
    )
    return [
        {
            "id": str(env.id),
            "name": env.name,
            "scope": env.scope,
            "description": env.description,
            "base_image": env.base_image,
            "is_default": env.is_default,
        }
        async for env in qs
    ]


@mcp.tool()
async def get_environment(
    name_or_id: Annotated[str, Field(description="The environment name or UUID to look up.")],
) -> dict | None:
    """Look up one sandbox environment by name or UUID. Returns ``None`` if not found
    in the caller's visible scopes (own USER envs plus all GLOBAL envs).

    Secret env-var values are masked as ``"******"``.
    """
    from django.db.models import Q

    user = await get_current_user()
    qs = SandboxEnvironment.objects.filter(Q(scope=Scope.USER, user=user) | Q(scope=Scope.GLOBAL))
    env: SandboxEnvironment | None = None
    if looks_like_uuid(name_or_id):
        env = await qs.filter(pk=name_or_id).afirst()
    if env is None:
        env = await qs.filter(name=name_or_id).afirst()
    if env is None:
        return None
    return {
        "id": str(env.id),
        "name": env.name,
        "scope": env.scope,
        "description": env.description,
        "base_image": env.base_image,
        "network_enabled": env.network_enabled,
        "memory_bytes": env.memory_bytes,
        "cpus": float(env.cpus) if env.cpus is not None else None,
        "is_default": env.is_default,
        "env_vars": [
            {
                "name": r["name"],
                "value": "******" if r.get("is_secret") else r["value"],
                "is_secret": bool(r.get("is_secret")),
            }
            for r in (env.env_vars or [])
        ],
    }
