import asyncio
import json
import logging
import uuid as uuid_mod
from typing import TYPE_CHECKING, Annotated

from activity.models import TriggerType
from activity.services import acreate_activity
from django_tasks_db.models import DBTaskResult
from jobs.tasks import run_job_task
from mcp.server.auth.settings import AuthSettings
from mcp.server.fastmcp import FastMCP
from mcp.server.transport_security import TransportSecuritySettings
from notifications.choices import NotifyOn  # noqa: TC002 - required at runtime for MCP tool schema
from pydantic import Field

from automation.agent.results import parse_agent_result
from codebase.clients import RepoClient
from core.conf import settings as core_settings
from mcp_server.auth import DjangoOAuthTokenVerifier, get_current_user

if TYPE_CHECKING:
    from codebase.base import Repository

logger = logging.getLogger("daiv.mcp_server")

_external_url = str(core_settings.EXTERNAL_URL).rstrip("/")

mcp = FastMCP(
    name="DAIV",
    instructions="""\
DAIV is an autonomous coding agent that operates on Git repositories (GitLab and GitHub). \
It reads, writes, and edits files, runs shell commands in a sandbox, and debugs CI/CD pipelines.

**Automatic post-job steps — do NOT ask for these in `prompt`.** When a job produces code \
changes, DAIV automatically commits, pushes to a newly created branch, and opens or updates \
a merge/pull request. The branch name, commit message, and MR/PR title and description are \
generated by DAIV from the diff — do NOT supply them, and do NOT instruct the agent to \
"commit", "push", "create a branch", or "open a PR/MR". Such instructions waste tokens and \
can mislead the agent. The `submit_job` response includes `merge_request_url` when a PR/MR \
was created or updated.

Use `list_repositories` to discover available repositories by name or topic. \
If the user already knows the `repo_id`, skip discovery and call `submit_job` directly.

Write specific prompts describing the intended change: include file paths, function names, \
error messages, or existing branch names to iterate on. Vague requests produce poor results.

`ref` is the STARTING POINT (base branch or commit SHA), not a target branch name. \
Omit it to start from the repository default branch. To add another commit to an existing \
DAIV MR/PR, pass that MR/PR's source branch as `ref` — DAIV will reuse the branch.

Jobs are rate-limited per user. Long-running jobs may exceed the 10-minute polling window; \
continue polling with `get_job_status` if the result is not yet available.\
""",
    stateless_http=True,
    transport_security=TransportSecuritySettings(enable_dns_rebinding_protection=False),
    auth=AuthSettings(issuer_url=_external_url, resource_server_url=f"{_external_url}/mcp", required_scopes=["mcp"]),
    token_verifier=DjangoOAuthTokenVerifier(),
)


TERMINAL_STATUSES = {"SUCCESSFUL", "FAILED"}
POLL_INTERVAL = 2.0
MAX_POLL_DURATION = 600.0  # 10 minutes


@mcp.tool()
async def submit_job(
    repo_id: Annotated[
        str,
        Field(
            description=(
                'Repository identifier. Use "owner/repo" for GitHub or the full project path for GitLab'
                ' (e.g. "group/project" or "group/subgroup/project").'
            )
        ),
    ],
    prompt: Annotated[
        str,
        Field(
            description=(
                "Task instruction for the agent. Describe the intended change — do NOT ask the agent"
                " to commit, push, create a branch, or open a merge/pull request; those steps run"
                " automatically after the job, and DAIV generates the branch name, commit message,"
                " and MR/PR title/description itself. Be specific: include file paths, function"
                " names, error messages, or existing branch names to iterate on."
            )
        ),
    ],
    ref: Annotated[
        str | None,
        Field(
            description=(
                "Starting point for the job (base branch name or commit SHA). Defaults to the"
                " repository's default branch. This is the base DAIV branches from — not a target"
                " branch name to create. To add another commit to an existing DAIV MR/PR, pass its"
                " source branch here and DAIV will reuse it."
            )
        ),
    ] = None,
    use_max: Annotated[
        bool, Field(description="Use the max model configuration (more capable model with thinking set to high).")
    ] = False,
    notify_on: Annotated[
        NotifyOn | None,
        Field(
            description=(
                "When to receive notifications for this job. When omitted, falls back to the user's default preference."
            )
        ),
    ] = None,
    wait: Annotated[
        bool,
        Field(
            description=(
                "When true, blocks until the job completes (up to 10 minutes) and returns the full result"
                " instead of just the job ID."
            )
        ),
    ] = False,
) -> str:
    """Submit a job to the DAIV agent for a repository."""
    try:
        result = await run_job_task.aenqueue(repo_id=repo_id, prompt=prompt, ref=ref, use_max=use_max)
    except Exception:
        logger.exception("Failed to enqueue MCP job for repo_id=%s", repo_id)
        return json.dumps({"error": f"Failed to submit job for repository '{repo_id}'. Please try again later."})

    job_id = str(result.id)
    mcp_user = None
    try:
        mcp_user = await get_current_user()
    except Exception:
        logger.exception("Failed to resolve current user for MCP job %s", job_id)

    try:
        await acreate_activity(
            trigger_type=TriggerType.MCP_JOB,
            task_result_id=result.id,
            repo_id=repo_id,
            ref=ref or "",
            prompt=prompt,
            use_max=use_max,
            user=mcp_user,
            notify_on=notify_on,
        )
    except Exception:
        logger.exception("Failed to create activity for MCP job %s", job_id)

    logger.info("MCP job submitted: job_id=%s, repo_id=%s", job_id, repo_id)

    if not wait:
        return json.dumps({"job_id": job_id})

    return await _poll_job_until_complete(job_id)


def _build_job_response(db_result: DBTaskResult) -> str:
    """Build a JSON response string from a DBTaskResult."""
    error = "Job execution failed." if db_result.status == "FAILED" else None
    parsed = parse_agent_result(db_result.return_value)
    return json.dumps({
        "job_id": str(db_result.id),
        "status": db_result.status,
        "result": parsed["response"] or None,
        "merge_request_url": parsed["merge_request_web_url"],
        "error": error,
        "created_at": db_result.enqueued_at.isoformat() if db_result.enqueued_at else None,
        "started_at": db_result.started_at.isoformat() if db_result.started_at else None,
        "finished_at": db_result.finished_at.isoformat() if db_result.finished_at else None,
    })


async def _poll_job_until_complete(job_id: str) -> str:
    """Poll a job until it reaches a terminal status or the timeout is exceeded."""
    job_uuid = uuid_mod.UUID(job_id)
    elapsed = 0.0
    last_result: DBTaskResult | None = None

    while elapsed < MAX_POLL_DURATION:
        await asyncio.sleep(POLL_INTERVAL)
        elapsed += POLL_INTERVAL

        try:
            last_result = await DBTaskResult.objects.aget(id=job_uuid, task_path=run_job_task.module_path)
        except DBTaskResult.DoesNotExist:
            logger.debug("Job %s not yet available, retrying (%.0fs elapsed)", job_id, elapsed)
            continue
        except Exception:
            logger.exception("Failed to poll job status for job_id=%s", job_id)
            return json.dumps({"error": "Failed to retrieve job status. Please try again later.", "job_id": job_id})

        if last_result.status in TERMINAL_STATUSES:
            return _build_job_response(last_result)

    # Timeout — return current status so the caller isn't left without info
    if last_result is not None:
        logger.info(
            "Polling timeout for job_id=%s after %.0fs, returning current status: %s",
            job_id,
            elapsed,
            last_result.status,
        )
        return _build_job_response(last_result)

    logger.warning("Polling timeout for job_id=%s after %.0fs, job never appeared in database", job_id, elapsed)
    return json.dumps({
        "error": f"Job '{job_id}' was submitted but has not appeared yet after {int(MAX_POLL_DURATION)}s. "
        "The task queue may be backed up. Use get_job_status to check later.",
        "job_id": job_id,
    })


@mcp.tool()
async def get_job_status(
    job_id: Annotated[str, Field(description="The job ID returned by submit_job.")],
    wait: Annotated[
        bool,
        Field(
            description=(
                "When true, blocks until the job completes (up to 10 minutes) instead of returning immediately."
            )
        ),
    ] = False,
) -> str:
    """Get the status and result of a previously submitted job. Status is one of: READY, RUNNING, SUCCESSFUL, FAILED."""
    try:
        job_uuid = uuid_mod.UUID(job_id)
    except ValueError:
        return json.dumps({"error": "Invalid job_id format."})

    try:
        db_result = await DBTaskResult.objects.aget(id=job_uuid, task_path=run_job_task.module_path)
    except DBTaskResult.DoesNotExist:
        if wait:
            return await _poll_job_until_complete(job_id)
        return json.dumps({"error": "Job not found."})
    except Exception:
        logger.exception("Failed to retrieve job status for job_id=%s", job_id)
        return json.dumps({"error": "Failed to retrieve job status. Please try again later."})

    if wait and db_result.status not in TERMINAL_STATUSES:
        return await _poll_job_until_complete(job_id)

    return _build_job_response(db_result)


MAX_REPOSITORIES = 40


def _serialize_repositories(repos: list[Repository]) -> list[dict]:
    """Convert a list of Repository objects to serializable dicts."""
    return [repo.model_dump(include={"slug", "name", "html_url", "default_branch", "topics"}) for repo in repos]


@mcp.tool()
async def list_repositories(
    search: Annotated[str | None, Field(description="Filter repositories by name (partial match).")] = None,
    topics: Annotated[list[str] | None, Field(description="Filter repositories by topic tags.")] = None,
) -> str:
    """
    List repositories accessible to DAIV, optionally filtered by name or topic.
    Results may be truncated; use search or topics to narrow down.
    """
    # Fetch one extra to detect truncation without loading everything
    fetch_limit = MAX_REPOSITORIES + 1
    try:
        client = RepoClient.create_instance()
        repos = await asyncio.to_thread(client.list_repositories, search=search, topics=topics, limit=fetch_limit)
    except Exception:
        logger.exception("Failed to list repositories")
        return json.dumps({"error": "Failed to list repositories. Please try again later."})

    truncated = len(repos) > MAX_REPOSITORIES
    result: dict = {"repositories": _serialize_repositories(repos[:MAX_REPOSITORIES])}
    if truncated:
        result["warning"] = (
            f"Only the first {MAX_REPOSITORIES} repositories are shown. "
            "There are more results available. Ask the user to provide a search term or topic to narrow down."
        )
    return json.dumps(result)
