import asyncio
import json
import logging
import uuid as uuid_mod
from typing import TYPE_CHECKING, Annotated

from activity.models import TriggerType
from activity.services import acreate_activity
from django_tasks_db.models import DBTaskResult
from jobs.tasks import run_job_task
from mcp.server.auth.settings import AuthSettings
from mcp.server.fastmcp import FastMCP
from mcp.server.transport_security import TransportSecuritySettings
from notifications.choices import NotifyOn  # noqa: TC002 - required at runtime for MCP tool schema
from pydantic import BaseModel, Field

from automation.agent.results import parse_agent_result
from codebase.clients import RepoClient
from core.conf import settings as core_settings
from mcp_server.auth import DjangoOAuthTokenVerifier, get_current_user

if TYPE_CHECKING:
    from codebase.base import Repository

logger = logging.getLogger("daiv.mcp_server")

_external_url = str(core_settings.EXTERNAL_URL).rstrip("/")

mcp = FastMCP(
    name="DAIV",
    instructions="""\
DAIV is an autonomous coding agent that operates on Git repositories (GitLab and GitHub). \
It reads, writes, and edits files, runs shell commands in a sandbox, and debugs CI/CD pipelines.

**Automatic post-job steps — do NOT ask for these in `prompt`.** When a job produces code \
changes, DAIV automatically commits, pushes to a newly created branch, and opens a \
merge/pull request. The branch name, commit message, and MR/PR title and description are \
generated by DAIV from the diff — do NOT supply them, and do NOT instruct the agent to \
"commit", "push", "create a branch", or "open a PR/MR". Such instructions waste tokens and \
can mislead the agent. Each `submit_job` call produces its own branch and its own MR/PR — \
the response includes `merge_request_url` when one was created.

Use `list_repositories` to discover available repositories by name or topic. \
If the user already knows the `repo_id`, skip discovery and call `submit_job` directly.

Write specific prompts describing the intended change: include file paths, function names, \
or error messages. Vague requests produce poor results.

`ref` is the STARTING POINT the agent reads from (base branch or commit SHA), not a target \
branch name. Omit it to start from the repository default branch. Pass an existing branch \
name to work from that branch's state — DAIV will still publish the result to a new branch \
and open a new MR/PR.

Jobs are rate-limited per user. Long-running jobs may exceed the 10-minute polling window; \
continue polling with `get_job_status` if the result is not yet available.\
""",
    stateless_http=True,
    transport_security=TransportSecuritySettings(enable_dns_rebinding_protection=False),
    auth=AuthSettings(issuer_url=_external_url, resource_server_url=f"{_external_url}/mcp", required_scopes=["mcp"]),
    token_verifier=DjangoOAuthTokenVerifier(),
)


TERMINAL_STATUSES = {"SUCCESSFUL", "FAILED"}
POLL_INTERVAL = 2.0
MAX_POLL_DURATION = 600.0  # 10 minutes
MAX_REPOS_PER_SUBMIT = 20


class RepoSubmitSpec(BaseModel):
    repo_id: str = Field(description='Repository identifier. "owner/repo" for GitHub or full project path for GitLab.')
    ref: str | None = Field(
        default=None, description="Git reference (branch name or commit SHA). None / empty string = default branch."
    )


@mcp.tool()
async def submit_job(
    repos: Annotated[
        list[RepoSubmitSpec], Field(min_length=1, max_length=20, description="1-20 repositories to run against.")
    ],
    prompt: Annotated[
        str,
        Field(
            description=(
                "Task instruction for the agent. Describe the intended change — do NOT ask the agent"
                " to commit, push, create a branch, or open a merge/pull request; those steps run"
                " automatically after the job, and DAIV generates the branch name, commit message,"
                " and MR/PR title/description itself. Be specific: include file paths, function"
                " names, or error messages. The same prompt runs independently against each repository."
            )
        ),
    ],
    use_max: Annotated[
        bool, Field(description="Use the max model configuration (more capable model with thinking set to high).")
    ] = False,
    notify_on: Annotated[
        NotifyOn | None,
        Field(
            description=(
                "When to receive notifications for each job. When omitted, falls back to the user's default preference."
            )
        ),
    ] = None,
    wait: Annotated[
        bool,
        Field(
            description=(
                "When true, blocks until every job in the batch completes (up to 10 minutes total)"
                " and returns each job's full result."
            )
        ),
    ] = False,
) -> str:
    """Submit a batch of agent jobs. Each repository runs as an independent job.

    Returns ``{batch_id, jobs: [{job_id, repo_id, ref}], failed: [...]}``. Each job runs
    independently; poll with ``get_job_status`` per job_id or pass ``wait=true``.
    """
    # Defensive validation: FastMCP only validates at the protocol layer; direct calls bypass it.
    if not repos:
        return json.dumps({"error": "At least one repository is required."})
    if len(repos) > MAX_REPOS_PER_SUBMIT:
        return json.dumps({"error": f"At most {MAX_REPOS_PER_SUBMIT} repositories allowed per submission."})

    # Coerce raw dict inputs (from direct Python calls / MCP protocol) into RepoSubmitSpec.
    repos = [spec if isinstance(spec, RepoSubmitSpec) else RepoSubmitSpec(**spec) for spec in repos]

    mcp_user = None
    try:
        mcp_user = await get_current_user()
    except Exception:
        logger.exception("Failed to resolve current user for MCP submit_job")

    batch_id = str(uuid_mod.uuid4())
    jobs: list[dict] = []
    failed: list[dict] = []
    job_ids: list[str] = []

    for spec in repos:
        ref_for_task = spec.ref or None
        try:
            task = await run_job_task.aenqueue(repo_id=spec.repo_id, prompt=prompt, ref=ref_for_task, use_max=use_max)
        except Exception as err:
            logger.exception("Failed to enqueue MCP job for repo_id=%s", spec.repo_id)
            failed.append({"repo_id": spec.repo_id, "ref": spec.ref, "error": f"{type(err).__name__}: {err}"})
            continue

        try:
            await acreate_activity(
                trigger_type=TriggerType.MCP_JOB,
                task_result_id=task.id,
                repo_id=spec.repo_id,
                ref=spec.ref or "",
                prompt=prompt,
                use_max=use_max,
                user=mcp_user,
                notify_on=notify_on,
                batch_id=uuid_mod.UUID(batch_id),
            )
        except Exception:
            logger.exception("Failed to create activity for MCP job %s (orphan job running)", task.id)

        jobs.append({"job_id": str(task.id), "repo_id": spec.repo_id, "ref": spec.ref})
        job_ids.append(str(task.id))

    logger.info("MCP batch submitted: batch_id=%s count=%d failures=%d", batch_id, len(jobs), len(failed))

    response: dict = {"batch_id": batch_id, "jobs": jobs, "failed": failed}
    if not wait:
        return json.dumps(response)

    return await _poll_batch_until_complete(batch_id, job_ids, response)


def _build_job_response_dict(db_result: DBTaskResult) -> dict:
    """Build a dict response from a DBTaskResult (shared by single + batch paths)."""
    error = "Job execution failed." if db_result.status == "FAILED" else None
    parsed = parse_agent_result(db_result.return_value)
    return {
        "job_id": str(db_result.id),
        "status": db_result.status,
        "result": parsed["response"] or None,
        "merge_request_url": parsed["merge_request_web_url"],
        "error": error,
        "created_at": db_result.enqueued_at.isoformat() if db_result.enqueued_at else None,
        "started_at": db_result.started_at.isoformat() if db_result.started_at else None,
        "finished_at": db_result.finished_at.isoformat() if db_result.finished_at else None,
    }


def _build_job_response(db_result: DBTaskResult) -> str:
    """Build a JSON response string from a DBTaskResult."""
    return json.dumps(_build_job_response_dict(db_result))


async def _poll_batch_until_complete(batch_id: str, job_ids: list[str], enqueue_response: dict) -> str:
    """Poll every job in the batch until terminal or the 10-minute budget is exhausted."""
    if not job_ids:
        return json.dumps(enqueue_response)

    job_uuids = [uuid_mod.UUID(j) for j in job_ids]
    elapsed = 0.0
    results_by_id: dict[str, DBTaskResult] = {}

    while elapsed < MAX_POLL_DURATION and len(results_by_id) < len(job_uuids):
        await asyncio.sleep(POLL_INTERVAL)
        elapsed += POLL_INTERVAL

        try:
            async for row in DBTaskResult.objects.filter(id__in=job_uuids, task_path=run_job_task.module_path):
                if row.status in TERMINAL_STATUSES:
                    results_by_id[str(row.id)] = row
        except Exception:
            logger.exception("Failed to poll batch_id=%s", batch_id)
            break

    return json.dumps({
        "batch_id": batch_id,
        "jobs": enqueue_response["jobs"],
        "failed": enqueue_response["failed"],
        "statuses": [
            _build_job_response_dict(results_by_id[jid])
            if jid in results_by_id
            else {"job_id": jid, "status": "PENDING"}
            for jid in job_ids
        ],
    })


async def _poll_job_until_complete(job_id: str) -> str:
    """Poll a job until it reaches a terminal status or the timeout is exceeded."""
    job_uuid = uuid_mod.UUID(job_id)
    elapsed = 0.0
    last_result: DBTaskResult | None = None

    while elapsed < MAX_POLL_DURATION:
        await asyncio.sleep(POLL_INTERVAL)
        elapsed += POLL_INTERVAL

        try:
            last_result = await DBTaskResult.objects.aget(id=job_uuid, task_path=run_job_task.module_path)
        except DBTaskResult.DoesNotExist:
            logger.debug("Job %s not yet available, retrying (%.0fs elapsed)", job_id, elapsed)
            continue
        except Exception:
            logger.exception("Failed to poll job status for job_id=%s", job_id)
            return json.dumps({"error": "Failed to retrieve job status. Please try again later.", "job_id": job_id})

        if last_result.status in TERMINAL_STATUSES:
            return _build_job_response(last_result)

    # Timeout — return current status so the caller isn't left without info
    if last_result is not None:
        logger.info(
            "Polling timeout for job_id=%s after %.0fs, returning current status: %s",
            job_id,
            elapsed,
            last_result.status,
        )
        return _build_job_response(last_result)

    logger.warning("Polling timeout for job_id=%s after %.0fs, job never appeared in database", job_id, elapsed)
    return json.dumps({
        "error": f"Job '{job_id}' was submitted but has not appeared yet after {int(MAX_POLL_DURATION)}s. "
        "The task queue may be backed up. Use get_job_status to check later.",
        "job_id": job_id,
    })


@mcp.tool()
async def get_job_status(
    job_id: Annotated[str, Field(description="The job ID returned by submit_job.")],
    wait: Annotated[
        bool,
        Field(
            description=(
                "When true, blocks until the job completes (up to 10 minutes) instead of returning immediately."
            )
        ),
    ] = False,
) -> str:
    """Get the status and result of a previously submitted job. Status is one of: READY, RUNNING, SUCCESSFUL, FAILED."""
    try:
        job_uuid = uuid_mod.UUID(job_id)
    except ValueError:
        return json.dumps({"error": "Invalid job_id format."})

    try:
        db_result = await DBTaskResult.objects.aget(id=job_uuid, task_path=run_job_task.module_path)
    except DBTaskResult.DoesNotExist:
        if wait:
            return await _poll_job_until_complete(job_id)
        return json.dumps({"error": "Job not found."})
    except Exception:
        logger.exception("Failed to retrieve job status for job_id=%s", job_id)
        return json.dumps({"error": "Failed to retrieve job status. Please try again later."})

    if wait and db_result.status not in TERMINAL_STATUSES:
        return await _poll_job_until_complete(job_id)

    return _build_job_response(db_result)


MAX_REPOSITORIES = 40


def _serialize_repositories(repos: list[Repository]) -> list[dict]:
    """Convert a list of Repository objects to serializable dicts."""
    return [repo.model_dump(include={"slug", "name", "html_url", "default_branch", "topics"}) for repo in repos]


@mcp.tool()
async def list_repositories(
    search: Annotated[str | None, Field(description="Filter repositories by name (partial match).")] = None,
    topics: Annotated[list[str] | None, Field(description="Filter repositories by topic tags.")] = None,
) -> str:
    """
    List repositories accessible to DAIV, optionally filtered by name or topic.
    Results may be truncated; use search or topics to narrow down.
    """
    # Fetch one extra to detect truncation without loading everything
    fetch_limit = MAX_REPOSITORIES + 1
    try:
        client = RepoClient.create_instance()
        repos = await asyncio.to_thread(client.list_repositories, search=search, topics=topics, limit=fetch_limit)
    except Exception:
        logger.exception("Failed to list repositories")
        return json.dumps({"error": "Failed to list repositories. Please try again later."})

    truncated = len(repos) > MAX_REPOSITORIES
    result: dict = {"repositories": _serialize_repositories(repos[:MAX_REPOSITORIES])}
    if truncated:
        result["warning"] = (
            f"Only the first {MAX_REPOSITORIES} repositories are shown. "
            "There are more results available. Ask the user to provide a search term or topic to narrow down."
        )
    return json.dumps(result)
