# Generated by Django 6.0.6 on 2026-06-13 09:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("activity", "0015_activity_agent_override_fields")]

    operations = [
        migrations.CreateModel(
            name="RepositoryMemory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("repo_id", models.CharField(max_length=255, unique=True, verbose_name="repository")),
                ("content", models.TextField(blank=True, default="", verbose_name="content")),
                (
                    "last_consolidated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last consolidated at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={"verbose_name": "Repository memory", "verbose_name_plural": "Repository memories"},
        ),
        migrations.CreateModel(
            name="MemoryObservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("repo_id", models.CharField(db_index=True, max_length=255, verbose_name="repository")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("build_test", "Build & test"),
                            ("codebase_fact", "Codebase fact"),
                            ("pitfall", "Pitfall"),
                            ("reviewer_preference", "Reviewer preference"),
                            ("workflow", "Workflow"),
                        ],
                        max_length=32,
                        verbose_name="category",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("consolidated", "Consolidated"), ("discarded", "Discarded")],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_observations",
                        to="activity.activity",
                        verbose_name="activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory observation",
                "verbose_name_plural": "Memory observations",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["repo_id", "status"], name="memory_obs_repo_status_idx")],
            },
        ),
    ]
