# Generated by Django 6.0.7 on 2026-08-03 21:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent_sessions", "0004_runenvelope"), ("memory", "0002_swap_activity_fk_to_run")]

    operations = [
        migrations.CreateModel(
            name="MemoryEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("repo_id", models.CharField(db_index=True, max_length=255, verbose_name="repository")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("build_test", "Build & test"),
                            ("codebase_fact", "Codebase fact"),
                            ("pitfall", "Pitfall"),
                            ("reviewer_preference", "Reviewer preference"),
                            ("workflow", "Workflow"),
                        ],
                        max_length=32,
                        verbose_name="category",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("superseded", "Superseded")],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="created at"),
                ),
                (
                    "last_confirmed_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="last confirmed at"),
                ),
                (
                    "observations",
                    models.ManyToManyField(
                        blank=True, related_name="entries", to="memory.memoryobservation", verbose_name="observations"
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_entries",
                        to="agent_sessions.run",
                        verbose_name="source run",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="memory.memoryentry",
                        verbose_name="superseded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory entry",
                "verbose_name_plural": "Memory entries",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["repo_id", "status"], name="memory_entry_repo_status_idx")],
            },
        )
    ]
