# Generated by Django 6.0.7 on 2026-08-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("memory", "0004_backfill_entries_from_documents")]

    operations = [
        migrations.AddField(
            model_name="repositorymemory",
            name="last_attempted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="last attempted at"),
        )
    ]
