# Generated by Django 6.0.4 on 2026-04-09 10:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("schedules", "0005_add_use_max_to_scheduledjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("api_job", "API Job"),
                            ("mcp_job", "MCP Job"),
                            ("schedule", "Scheduled Job"),
                            ("issue_webhook", "Issue Webhook"),
                            ("mr_webhook", "MR/PR Webhook"),
                        ],
                        max_length=20,
                        verbose_name="trigger type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("repo_id", models.CharField(max_length=255, verbose_name="repository")),
                ("ref", models.CharField(blank=True, default="", max_length=255, verbose_name="branch / ref")),
                ("prompt", models.TextField(blank=True, default="", verbose_name="prompt")),
                ("issue_iid", models.PositiveIntegerField(blank=True, null=True, verbose_name="issue IID")),
                (
                    "merge_request_iid",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="merge request IID"),
                ),
                (
                    "mention_comment_id",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="mention comment ID"),
                ),
                ("result_summary", models.TextField(blank=True, default="", verbose_name="result summary")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="error message")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="started at")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="finished at")),
                (
                    "scheduled_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="schedules.scheduledjob",
                        verbose_name="scheduled job",
                    ),
                ),
                (
                    "task_result",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to="django_tasks_database.dbtaskresult",
                        verbose_name="task result",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["trigger_type", "-created_at"], name="activity_trigger_created_idx"),
                    models.Index(fields=["repo_id", "-created_at"], name="activity_repo_created_idx"),
                    models.Index(fields=["status", "-created_at"], name="activity_status_created_idx"),
                    models.Index(fields=["scheduled_job", "-created_at"], name="activity_schedule_created_idx"),
                ],
            },
        )
    ]
