# Generated by Django 6.0.4 on 2026-04-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0002_migrate_scheduled_job_runs")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="merge_request_web_url",
            field=models.URLField(blank=True, default="", max_length=500, verbose_name="merge request URL"),
        )
    ]
