# Generated by Django 6.0.4 on 2026-04-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0004_activity_external_username_activity_user_and_more")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="cost_usd",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True, verbose_name="cost (USD)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="input_tokens",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="input tokens"),
        ),
        migrations.AddField(
            model_name="activity",
            name="output_tokens",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="output tokens"),
        ),
        migrations.AddField(
            model_name="activity",
            name="total_tokens",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="total tokens"),
        ),
        migrations.AddField(
            model_name="activity",
            name="usage_by_model",
            field=models.JSONField(blank=True, null=True, verbose_name="usage by model"),
        ),
    ]
