# Generated by Django 6.0.4 on 2026-04-12 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0004_add_user_field"),
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("schedules", "0006_remove_scheduledjobrun_sched_run_job_created_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="external_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Git platform username from webhook payload. Used to backfill user when they later join DAIV.",
                max_length=255,
                verbose_name="external username",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                condition=models.Q(("external_username__gt", "")),
                fields=["external_username", "-created_at"],
                name="activity_ext_user_created_idx",
            ),
        ),
    ]
