# Generated by Django 6.0.4 on 2026-04-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0005_activity_usage_cost")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="use_max",
            field=models.BooleanField(default=False, verbose_name="use max model"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("api_job", "API Run"),
                    ("mcp_job", "MCP Run"),
                    ("schedule", "Scheduled Run"),
                    ("ui_job", "UI Run"),
                    ("issue_webhook", "Issue Webhook"),
                    ("mr_webhook", "MR/PR Webhook"),
                ],
                max_length=20,
                verbose_name="trigger type",
            ),
        ),
    ]
