# Generated by Django 6.0.4 on 2026-04-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0006_activity_use_max_uijob")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="notify_on",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("always", "Always"),
                    ("on_success", "On success only"),
                    ("on_failure", "On failure only"),
                ],
                help_text="Per-run override. When null, falls back to the initiating user's notify_on_jobs (or, for schedule runs, copied from ScheduledJob.notify_on at creation time).",
                max_length=16,
                null=True,
                verbose_name="notify on",
            ),
        )
    ]
