# Generated by Django 6.0.4 on 2026-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0007_activity_notify_on")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="batch_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Shared identifier for activities from the same submission.",
                null=True,
                verbose_name="batch ID",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="notify_on",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("always", "Always"),
                    ("on_success", "On success only"),
                    ("on_failure", "On failure only"),
                ],
                help_text="Per-run override. When null, the notifier falls back to ScheduledJob.notify_on (for schedule runs) or to the initiating user's notify_on_jobs preference.",
                max_length=16,
                null=True,
                verbose_name="notify on",
            ),
        ),
    ]
