# Generated by Django 6.0.4 on 2026-04-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0008_activity_batch_id")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="thread_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="LangGraph checkpoint key. Lets chat resume this run.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="thread ID",
            ),
        )
    ]
