# Generated by Django 6.0.4 on 2026-04-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0009_activity_thread_id")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="title",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="title"),
        )
    ]
