# Generated by Django 6.0.4 on 2026-05-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0010_title")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="thread_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="LangGraph checkpoint key. Lets chat resume this run.",
                max_length=64,
                null=True,
                verbose_name="thread ID",
            ),
        )
    ]
