# Generated by Django 6.0.4 on 2026-05-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0011_drop_thread_id_unique")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="repo_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="repository"),
        )
    ]
