# Generated by Django 6.0.4 on 2026-05-10 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("activity", "0011_drop_thread_id_unique"), ("sandbox_envs", "0002_seed_global_default")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="sandbox_environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="sandbox_envs.sandboxenvironment",
                verbose_name="sandbox environment",
            ),
        )
    ]
