# Generated by Django 6.0.5 on 2026-05-20 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0012_activity_sandbox_environment"),
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("sandbox_envs", "0004_repo_ids"),
        ("schedules", "0014_scheduledjob_sandbox_environment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("READY", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESSFUL", "Successful"),
                    ("FAILED", "Failed"),
                ],
                default="READY",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AddIndex(
            model_name="activity", index=models.Index(fields=["thread_id", "status"], name="activity_thread_status_idx")
        ),
    ]
