# Generated by Django 6.0.5 on 2026-05-22 23:54

from django.db import migrations, models


def _resolve_max_model_spec(apps) -> str:
    SiteConfiguration = apps.get_model("core", "SiteConfiguration")
    config = SiteConfiguration.objects.first()
    if config is not None and getattr(config, "agent_max_model_name", ""):
        return config.agent_max_model_name
    # Match the hardcoded default in core.site_settings._build_field_defaults
    return "openrouter:anthropic/claude-opus-4.6"


def translate_use_max(apps, schema_editor):
    Activity = apps.get_model("activity", "Activity")
    spec = _resolve_max_model_spec(apps)
    # Reset use_max=False atomically with the translation so the boolean stays the
    # authoritative "this row was a max run" marker only for legacy rows the
    # migration didn't reach (and so reading use_max alone never reports a stale
    # True on rows already migrated to the new pair).
    Activity.objects.filter(use_max=True).update(agent_model=spec, agent_thinking_level="high", use_max=False)


def reverse_translate_use_max(apps, schema_editor):
    # Lossless reverse: only flip use_max=True on rows whose override exactly
    # matches the max preset. A user-chosen override (e.g. Haiku/low) must NOT
    # be re-labelled as a max run on rollback.
    Activity = apps.get_model("activity", "Activity")
    spec = _resolve_max_model_spec(apps)
    Activity.objects.filter(agent_model=spec, agent_thinking_level="high").update(use_max=True)


class Migration(migrations.Migration):
    dependencies = [("activity", "0014_one_active_per_thread"), ("core", "0009_drop_sandbox_overrides")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="agent_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Per-run model override (slug:model_name); empty = auto.",
                max_length=255,
                verbose_name="agent model",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="agent_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[("minimal", "Minimal"), ("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="",
                help_text="Per-run thinking effort; empty = inherit from repo config.",
                max_length=20,
                verbose_name="agent thinking level",
            ),
        ),
        migrations.RunPython(translate_use_max, reverse_translate_use_max),
    ]
