# Generated by Django 6.0.6 on 2026-07-07 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0015_activity_agent_override_fields"),
        # Data was already copied to sessions.Run before we drop the source table.
        # Note: sessions app is registered under the label "agent_sessions".
        ("agent_sessions", "0002_backfill_from_activity_and_chat"),
        # memory FK was moved off activity.Activity to sessions.Run.
        ("memory", "0002_swap_activity_fk_to_run"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="activity", name="activity_trigger_created_idx"),
        migrations.RemoveIndex(model_name="activity", name="activity_repo_created_idx"),
        migrations.RemoveIndex(model_name="activity", name="activity_status_created_idx"),
        migrations.RemoveIndex(model_name="activity", name="activity_schedule_created_idx"),
        migrations.RemoveIndex(model_name="activity", name="activity_user_created_idx"),
        migrations.RemoveIndex(model_name="activity", name="activity_ext_user_created_idx"),
        migrations.RemoveIndex(model_name="activity", name="activity_thread_status_idx"),
        migrations.RemoveConstraint(model_name="activity", name="activity_thread_id_nonempty"),
        migrations.RemoveConstraint(model_name="activity", name="activity_one_active_per_thread"),
        migrations.DeleteModel(name="Activity"),
    ]
