# Generated by Django 6.0.6 on 2026-07-07 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0015_activity_agent_override_fields"),
        # Data was already copied to sessions.Run before we drop the source table.
        # Note: sessions app is registered under the label "agent_sessions".
        ("agent_sessions", "0002_backfill_from_activity_and_chat"),
        # memory FK was moved off activity.Activity to sessions.Run.
        ("memory", "0002_swap_activity_fk_to_run"),
    ]

    operations = [
        # The table is dropped wholesale, so let a single DROP TABLE (CASCADE on PostgreSQL)
        # remove it together with all its indexes and constraints. Dropping each index/constraint
        # individually first — as the autodetector generates — fails on deployments whose
        # activity table drifted from migration history (e.g. the ``activity_thread_id_nonempty``
        # check that was never actually created), where RemoveConstraint raises "constraint does
        # not exist". SeparateDatabaseAndState keeps Django's state bookkeeping identical while
        # making the database side tolerant of that drift.
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.DeleteModel(name="Activity")],
            state_operations=[
                migrations.RemoveIndex(model_name="activity", name="activity_trigger_created_idx"),
                migrations.RemoveIndex(model_name="activity", name="activity_repo_created_idx"),
                migrations.RemoveIndex(model_name="activity", name="activity_status_created_idx"),
                migrations.RemoveIndex(model_name="activity", name="activity_schedule_created_idx"),
                migrations.RemoveIndex(model_name="activity", name="activity_user_created_idx"),
                migrations.RemoveIndex(model_name="activity", name="activity_ext_user_created_idx"),
                migrations.RemoveIndex(model_name="activity", name="activity_thread_status_idx"),
                migrations.RemoveConstraint(model_name="activity", name="activity_thread_id_nonempty"),
                migrations.RemoveConstraint(model_name="activity", name="activity_one_active_per_thread"),
                migrations.DeleteModel(name="Activity"),
            ],
        )
    ]
