# Generated by Django 6.0.4 on 2026-05-10 23:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="SandboxEnvironment",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(choices=[("user", "User"), ("global", "Global")], default="user", max_length=10),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                ("description", models.TextField(blank=True, default="", verbose_name="description")),
                ("base_image", models.CharField(blank=True, default="", max_length=255, verbose_name="base image")),
                (
                    "network_enabled",
                    models.BooleanField(blank=True, default=None, null=True, verbose_name="network enabled"),
                ),
                ("memory_bytes", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="memory (bytes)")),
                (
                    "cpus",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="CPUs"),
                ),
                ("_env_vars_encrypted", models.TextField(blank=True, editable=False, null=True)),
                ("is_default", models.BooleanField(default=False, verbose_name="is default")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sandbox_environments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "user")), fields=("user", "name"), name="env_user_name_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "global")), fields=("name",), name="env_global_name_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "global"), ("is_default", True)),
                        fields=("is_default",),
                        name="env_one_global_default",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("scope", "user"), ("user__isnull", False)),
                            models.Q(("scope", "global"), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="env_scope_user_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("is_default", False), ("scope", "global"), _connector="OR"),
                        name="env_default_only_on_global",
                    ),
                ],
            },
        )
    ]
