# Generated by Django 6.0.5 on 2026-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sandbox_envs", "0003_relax_base_image_lock")]

    operations = [
        migrations.AddField(
            model_name="sandboxenvironment",
            name="repo_ids",
            field=models.JSONField(blank=True, default=list, verbose_name="repo ids"),
        )
    ]
