# Generated by Django 6.0.6 on 2026-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sandbox_envs", "0004_repo_ids")]

    operations = [
        migrations.AddField(
            model_name="sandboxenvironment",
            name="_egress_secrets_encrypted",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="sandboxenvironment",
            name="egress_policy",
            field=models.JSONField(blank=True, default=None, null=True, verbose_name="egress policy"),
        ),
    ]
