"""Behavioral tests for the context-meter handler in ``chat-stream.js``.

Payloads are generated by ``context_usage_payload`` at test time, never hand-written:
the consumer is JS with hand-typed key literals — the exact shape of the
ASSISTANT_MESSAGE_EVENT failure — so a key renamed on either side alone must fail here.
"""

from __future__ import annotations

from automation.agent.events import CONTEXT_USAGE_EVENT, context_usage_payload
from automation.agent.usage_tracking import ResolvedWindow
from tests.unit_tests.chat.chat_stream_driver import run_chat_stream
from tests.unit_tests.jsdriver import requires_node

pytestmark = requires_node

BODY = """
const chat = registry.chat({ endpoint: "/api/chat" });
chat.scrollToBottom = () => {};
const turn = { id: "t", role: "assistant", segments: [], streaming: true };
chat.turns = [turn];
for (const value of payload.frames) {
  chat.dispatch({ type: "CUSTOM", name: payload.eventName, value }, turn, 0);
}
process.stdout.write(JSON.stringify({
  meter: chat.contextMeter,
  headroom: chat.contextHeadroom,
  figure: chat.contextFigure,
}));
"""


def _meter(*frames) -> dict:
    return run_chat_stream(BODY, {"eventName": CONTEXT_USAGE_EVENT, "frames": list(frames)})


def _payload(used, window, *, output_tokens=0, model="anthropic/claude-sonnet-4.6", cached=0) -> dict:
    return context_usage_payload(
        model=model,
        usage={
            "input_tokens": used - output_tokens,
            "output_tokens": output_tokens,
            "input_token_details": {"cache_read": cached},
        },
        window=ResolvedWindow(window, "genai_prices") if window else None,
    )


def test_the_handler_updates_the_ring_from_a_builder_payload():
    out = _meter(_payload(42_000, 100_000))

    assert out["meter"]["hasWindow"] is True
    assert out["meter"]["label"] == "42%"
    assert out["meter"]["fill"] == 42
    assert out["meter"]["tone"] == ""
    assert out["headroom"]["tone"] == "ok"


def test_count_only_when_the_window_is_unresolved():
    """No headroom sentence either: the hidden track and the "/ limit"-less figure are the
    absence, and a line restating it was the panel's noisiest row."""
    out = _meter(_payload(130_000, None))

    assert out["meter"]["hasWindow"] is False
    assert out["meter"]["showValue"] is True
    assert out["meter"]["label"]  # the compact count — locale-formatted, so just non-empty
    assert out["headroom"] is None


def test_the_fill_clamps_past_the_window_but_the_label_tells_the_truth():
    out = _meter(_payload(104_000, 100_000))

    assert out["meter"]["fill"] == 100
    assert out["meter"]["label"] == "104%"
    assert out["headroom"]["tone"] == "danger"


def test_the_label_floors_and_the_thresholds_compare_the_raw_ratio():
    just_under = _meter(_payload(74_900, 100_000))
    at_threshold = _meter(_payload(75_000, 100_000))

    assert just_under["meter"]["label"] == "74%"
    assert just_under["meter"]["tone"] == ""
    assert at_threshold["meter"]["label"] == "75%"
    assert at_threshold["meter"]["tone"] == "warn"


def test_ninety_percent_fires_danger():
    assert _meter(_payload(90_000, 100_000))["meter"]["tone"] == "danger"


def test_a_later_payload_replaces_the_reading():
    out = _meter(_payload(10_000, 100_000), _payload(90_000, 100_000))

    assert out["meter"]["tone"] == "danger"


def test_a_malformed_payload_leaves_the_meter_alone():
    out = _meter(_payload(10_000, 100_000), {"junk": True})

    assert out["meter"]["label"] == "10%"
