# Generated by Django 6.0.4 on 2026-04-13 22:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("event_type", models.CharField(max_length=64, verbose_name="event type")),
                ("source_type", models.CharField(blank=True, default="", max_length=64, verbose_name="source type")),
                ("source_id", models.CharField(blank=True, default="", max_length=64, verbose_name="source id")),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                ("body", models.TextField(verbose_name="body")),
                ("link_url", models.CharField(blank=True, default="", max_length=500, verbose_name="link URL")),
                ("context", models.JSONField(blank=True, default=dict, verbose_name="context")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="read at")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
            ],
            options={"ordering": ["-created"]},
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "channel_type",
                    models.CharField(choices=[("email", "Email")], max_length=32, verbose_name="channel type"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="attempts")),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True, verbose_name="last attempted at")),
                ("delivered_at", models.DateTimeField(blank=True, null=True, verbose_name="delivered at")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="error message")),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                        verbose_name="notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserChannelBinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "channel_type",
                    models.CharField(choices=[("email", "Email")], max_length=32, verbose_name="channel type"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                ("extra_config", models.JSONField(blank=True, default=dict, verbose_name="extra config")),
                ("is_verified", models.BooleanField(default=False, verbose_name="verified")),
                ("verified_at", models.DateTimeField(blank=True, null=True, verbose_name="verified at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_bindings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "read_at"], name="notif_recipient_read_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "-created"], name="notif_recipient_created_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["status", "last_attempted_at"], name="notif_delivery_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("notification", "channel_type"), name="notif_delivery_unique_channel"
            ),
        ),
        migrations.AddConstraint(
            model_name="userchannelbinding",
            constraint=models.UniqueConstraint(
                fields=("user", "channel_type", "address"), name="user_channel_binding_unique"
            ),
        ),
    ]
