# Generated by Django 6.0.4 on 2026-04-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("notifications", "0002_seed_email_bindings")]

    operations = [
        migrations.AlterField(
            model_name="notificationdelivery",
            name="channel_type",
            field=models.CharField(
                choices=[("email", "Email"), ("rocketchat", "Rocket Chat")], max_length=32, verbose_name="channel type"
            ),
        ),
        migrations.AlterField(
            model_name="userchannelbinding",
            name="channel_type",
            field=models.CharField(
                choices=[("email", "Email"), ("rocketchat", "Rocket Chat")], max_length=32, verbose_name="channel type"
            ),
        ),
    ]
