# Generated by Django 6.0.5 on 2026-05-12 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notificationdelivery_channel_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_type", "job_batch.finished")),
                fields=("recipient", "source_type", "source_id", "event_type"),
                name="notif_unique_per_batch_recipient",
            ),
        )
    ]
