# Generated by Django 6.0.5 on 2026-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("notifications", "0004_notification_notif_unique_per_batch_recipient")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job.finished", "Job finished"),
                    ("schedule.finished", "Schedule finished"),
                    ("job_batch.finished", "Job batch finished"),
                ],
                max_length=64,
                verbose_name="event type",
            ),
        )
    ]
