# Generated by Django 6.0.6 on 2026-07-08 16:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("notifications", "0005_event_type_choices")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="context",
            field=models.JSONField(
                blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name="context"
            ),
        )
    ]
