# Generated by Django 6.0.7 on 2026-07-17 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_alter_notification_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="notification", name="notif_unique_per_batch_recipient"),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job.finished", "Job finished"),
                    ("schedule.finished", "Schedule finished"),
                    ("job_batch.finished", "Job batch finished"),
                    ("run.feed", "Run feed"),
                ],
                max_length=64,
                verbose_name="event type",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_type__in", ["job_batch.finished", "run.feed"])),
                fields=("recipient", "source_type", "source_id", "event_type"),
                name="notif_unique_per_batch_recipient",
            ),
        ),
    ]
