# Generated by Django 6.0.7 on 2026-08-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("notifications", "0007_per_run_notification_dedup")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job.finished", "Job finished"),
                    ("schedule.finished", "Schedule finished"),
                    ("job_batch.finished", "Job batch finished"),
                    ("pipeline_watch.exhausted", "Pipeline watch gave up"),
                ],
                max_length=64,
                verbose_name="event type",
            ),
        )
    ]
