# Generated by Django 6.0.7 on 2026-08-26 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0008_pipeline_watch_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="notification", name="notif_unique_per_source_recipient"),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q((
                    "event_type__in",
                    ["job_batch.finished", "job.finished", "schedule.finished", "pipeline_watch.exhausted"],
                )),
                fields=("recipient", "source_type", "source_id", "event_type"),
                name="notif_unique_per_source_recipient",
            ),
        ),
    ]
