# Generated by Django 6.1.1 on 2026-09-30 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_telegram_channel_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="notification", name="notif_unique_per_source_recipient"),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job.finished", "Job finished"),
                    ("schedule.finished", "Schedule finished"),
                    ("job_batch.finished", "Job batch finished"),
                    ("pipeline_watch.exhausted", "Pipeline watch gave up"),
                    ("schedule_dispatch.failed", "Schedule can't run"),
                ],
                max_length=64,
                verbose_name="event type",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q((
                    "event_type__in",
                    [
                        "job_batch.finished",
                        "job.finished",
                        "schedule.finished",
                        "pipeline_watch.exhausted",
                        "schedule_dispatch.failed",
                    ],
                )),
                fields=("recipient", "source_type", "source_id", "event_type"),
                name="notif_unique_per_source_recipient",
            ),
        ),
    ]
