"""The Telegram webhook.

An unauthenticated ninja route following the GitLab precedent — ``hmac.compare_digest``
against a header secret, 401 on mismatch, both trailing-slash variants stacked on one handler
— with one deliberate divergence: **fail-closed**. ``validate_gitlab_webhook`` returns True
when no secret is configured; a blank stored secret here rejects every update instead. The
secret is generated by DAIV, so its absence means the sync never completed, and ``/stop``
carries no token — a fail-open route would let anyone who can reach it unbind users by
guessing chat ids.

The signature declares no pydantic payload on purpose: django-ninja answers a schema mismatch
with 422, and Telegram retries non-2xx updates then disables a webhook that keeps failing. So
everything except a bad secret is 2xx, and the body is parsed through the transport's lenient
schemas instead.

Sync, not ``async def`` like the GitLab callback: the work is an ORM write plus a best-effort
sendMessage, both synchronous, and a sync route avoids threading ``sync_to_async`` through the
command registry.
"""

from __future__ import annotations

import hmac
import logging

from django.http import HttpRequest  # noqa: TC002 - required at runtime by Django Ninja

from ninja import Router
from ninja.security import django_auth

from core.site_settings import site_settings
from notifications.api.telegram_handlers import MSG_PRIVATE_ONLY, handle_my_chat_member
from notifications.telegram.client import TGClient
from notifications.telegram.commands import get_command
from notifications.telegram.schemas import is_private_chat, parse_command, parse_update

logger = logging.getLogger("daiv.notifications")

# Closed by default so a future route here is authenticated unless it opts out; the callback
# below opts out with ``auth=None``, which ninja honours only because it is not ``NOT_SET``.
router = Router(tags=["notifications"], auth=django_auth)

_SECRET_HEADER = "X-Telegram-Bot-Api-Secret-Token"  # noqa: S105 — a header name, not a secret


def _secret_is_valid(request: HttpRequest) -> bool:
    secret = site_settings.telegram_webhook_secret
    if not secret:
        logger.warning("Telegram webhook rejected: no webhook secret stored (fail-closed)")
        return False
    header = request.headers.get(_SECRET_HEADER)
    if not header:
        logger.warning("Telegram webhook rejected: missing %s header", _SECRET_HEADER)
        return False
    # Encoded, not compared as str: compare_digest raises TypeError on a non-ASCII str, and the
    # header is attacker-controlled, so the str form turns a bad secret into a 500 instead of 401.
    if not hmac.compare_digest(header.encode(), secret.get_secret_value().encode()):
        logger.warning("Telegram webhook rejected: secret mismatch")
        return False
    return True


def _reply(chat_id: int, text: str) -> None:
    """Best-effort confirmation.

    A failed sendMessage must not turn a successful bind into a 500 and a retry storm.
    """
    try:
        # Resolved inside the try: from_site_settings reads an encrypted field, so it can hit the
        # DB and decrypt — either able to raise after the binding write has already committed.
        client = TGClient.from_site_settings()
        if client is None:
            logger.warning("Telegram: cannot reply to chat %s, no bot token configured", chat_id)
            return
        client.send_message({"chat_id": chat_id, "text": text})
    except Exception as exc:  # noqa: BLE001 — any failure here is cosmetic by construction
        logger.warning("Telegram: reply to chat %s failed: %s", chat_id, exc)


# Trailing slash on top: decorators apply bottom-up, and Django's reverse walks url_patterns
# backwards, so of two patterns sharing a name the last-registered (top) one is canonical.
@router.post("/callbacks/telegram/", response={204: None, 401: None}, auth=None, url_name="telegram_callback")
@router.post("/callbacks/telegram", response={204: None, 401: None}, auth=None, url_name="telegram_callback")
def telegram_callback(request: HttpRequest):
    """Dispatch one Telegram update. 401 for a bad secret; 2xx for everything else."""
    if not _secret_is_valid(request):
        return 401, None

    if not site_settings.telegram_enabled:
        # A failed deleteWebhook must not leave a live binding surface.
        logger.info("Telegram webhook received while the channel is disabled; ignoring")
        return 204, None

    update = parse_update(request.body)
    if update is None:
        return 204, None

    if update.my_chat_member is not None:
        handle_my_chat_member(update.my_chat_member)
        return 204, None

    message = update.message
    if message is None or message.chat is None or message.chat.id is None:
        return 204, None

    parsed = parse_command(message.text)
    if parsed is None:
        return 204, None

    name, argument = parsed
    command = get_command(name)
    if command is None:
        logger.info("Telegram: unknown command %r; ignoring", name)
        return 204, None

    # Resolved after the registry lookup so an unknown command in a group stays silent.
    if not is_private_chat(message.chat):
        _reply(message.chat.id, str(MSG_PRIVATE_ONLY))
        return 204, None

    if reply := command.handle(message.chat, argument):
        _reply(message.chat.id, reply)
    return 204, None
