# Generated by Django 6.0.3 on 2026-04-07 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("prompt", models.TextField(help_text="What the agent should do.", verbose_name="prompt")),
                (
                    "repo_id",
                    models.CharField(
                        help_text="Repository identifier, e.g. owner/repo.", max_length=255, verbose_name="repository"
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Git branch or ref. Leave blank for the default branch.",
                        max_length=255,
                        verbose_name="branch / ref",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekdays", "Weekdays"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Required when frequency is Custom. Five-field cron expression.",
                        max_length=100,
                        verbose_name="cron expression",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True, help_text="Time of day for non-hourly schedules.", null=True, verbose_name="time"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone for the schedule.",
                        max_length=63,
                        verbose_name="timezone",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="enabled")),
                ("next_run_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="next run at")),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="last run at")),
                ("last_run_task_id", models.UUIDField(blank=True, null=True, verbose_name="last run task ID")),
                ("run_count", models.PositiveIntegerField(default=0, verbose_name="run count")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Job",
                "verbose_name_plural": "Scheduled Jobs",
                "ordering": ["-created"],
                "indexes": [models.Index(fields=["is_enabled", "next_run_at"], name="sched_enabled_next_idx")],
            },
        )
    ]
