# Generated by Django 6.0.3 on 2026-04-07 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.AddConstraint(
            model_name="scheduledjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("frequency", "custom"), _negated=True),
                    models.Q(("cron_expression", ""), _negated=True),
                    _connector="OR",
                ),
                name="sched_custom_requires_cron",
            ),
        )
    ]
