# Generated by Django 6.0.3 on 2026-04-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more"),
        ("schedules", "0002_scheduledjob_sched_custom_requires_cron"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledjob",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Time of day (used for Daily, Weekdays, and Weekly frequencies).",
                null=True,
                verbose_name="time",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledJobRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                (
                    "scheduled_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="schedules.scheduledjob",
                        verbose_name="scheduled job",
                    ),
                ),
                (
                    "task_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_tasks_database.dbtaskresult",
                        verbose_name="task result",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Job Run",
                "verbose_name_plural": "Scheduled Job Runs",
                "ordering": ["-created"],
                "indexes": [models.Index(fields=["scheduled_job", "-created"], name="sched_run_job_created_idx")],
            },
        ),
    ]
