# Generated by Django 6.0.3 on 2026-04-08 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("schedules", "0003_alter_scheduledjob_time_scheduledjobrun")]

    operations = [migrations.RemoveField(model_name="scheduledjob", name="timezone")]
