# Generated by Django 6.0.4 on 2026-04-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0004_remove_scheduledjob_timezone")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="use_max",
            field=models.BooleanField(
                default=False,
                help_text="Use the more capable model with thinking set to high.",
                verbose_name="max mode",
            ),
        )
    ]
