# Generated by Django 6.0.4 on 2026-04-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0006_remove_scheduledjobrun_sched_run_job_created_idx_and_more")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="notify_on",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("always", "Always"),
                    ("on_success", "On success only"),
                    ("on_failure", "On failure only"),
                ],
                default="never",
                max_length=16,
                verbose_name="notify on",
            ),
        )
    ]
