# Generated by Django 6.0.4 on 2026-04-17 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0007_scheduledjob_notify_on"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other users CC'd on this schedule's finish notifications.",
                related_name="subscribed_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribers",
            ),
        )
    ]
