# Generated by Django 6.0.4 on 2026-04-23 08:54

from django.db import migrations, models


def backfill_repos_and_batch_id(apps, schema_editor):
    """Backfill ``repos`` from ``repo_id``/``ref`` and ``last_run_batch_id`` from ``last_run_task_id``."""
    ScheduledJob = apps.get_model("schedules", "ScheduledJob")
    for row in ScheduledJob.objects.all().iterator():
        row.repos = [{"repo_id": row.repo_id, "ref": row.ref or ""}]
        if row.last_run_task_id is not None:
            row.last_run_batch_id = row.last_run_task_id
        row.save(update_fields=["repos", "last_run_batch_id"])


def _noop_reverse(apps, schema_editor):
    """No-op reverse. Safe only before migration 0010 drops the scalar columns; after 0010
    reverse cannot reconstruct ``repo_id`` / ``ref`` / ``last_run_task_id`` from ``repos``.
    """
    return


class Migration(migrations.Migration):
    dependencies = [("schedules", "0008_scheduledjob_subscribers")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="last_run_batch_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="last run batch ID"),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="repos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {repo_id, ref} entries. 1-20 entries. Empty ref means the default branch.",
                verbose_name="repositories",
            ),
        ),
        migrations.RunPython(backfill_repos_and_batch_id, _noop_reverse),
    ]
