# Generated by Django 6.0.4 on 2026-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0009_scheduledjob_repos_last_run_batch_id")]

    operations = [
        migrations.RemoveField(model_name="scheduledjob", name="last_run_task_id"),
        migrations.RemoveField(model_name="scheduledjob", name="ref"),
        migrations.RemoveField(model_name="scheduledjob", name="repo_id"),
        migrations.AlterField(
            model_name="scheduledjob",
            name="repos",
            field=models.JSONField(
                help_text="List of {repo_id, ref} entries. 1-20 entries. Empty ref means the default branch.",
                verbose_name="repositories",
            ),
        ),
    ]
