# Generated by Django 6.0.4 on 2026-04-21 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0010_remove_scheduledjob_repo_id_ref_last_run_task_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="name")),
                ("description", models.TextField(blank=True, default="", verbose_name="description")),
                ("prompt", models.TextField(help_text="What the agent should do.", verbose_name="prompt")),
                (
                    "repos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "List of {repo_id, ref} entries that pre-fill the schedule's repo picker. "
                            "Leave empty to let users choose."
                        ),
                        verbose_name="default repositories",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekdays", "Weekdays"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="cron expression"),
                ),
                ("time", models.TimeField(blank=True, null=True, verbose_name="time")),
                ("use_max", models.BooleanField(default=False, verbose_name="max mode")),
                (
                    "notify_on",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("always", "Always"),
                            ("on_success", "On success only"),
                            ("on_failure", "On failure only"),
                        ],
                        default="never",
                        max_length=16,
                        verbose_name="notify on",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedule_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Template",
                "verbose_name_plural": "Schedule Templates",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("frequency", "custom"), _negated=True),
                            models.Q(("cron_expression", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="tpl_custom_requires_cron",
                    )
                ],
            },
        )
    ]
