# Generated by Django 6.0.5 on 2026-05-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0011_scheduletemplate")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this schedule was created from. Cleared if the template is later deleted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="schedules.scheduletemplate",
                verbose_name="source template",
            ),
        )
    ]
