# Generated by Django 6.0.5 on 2026-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0012_scheduledjob_source_template")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="run_at",
            field=models.DateTimeField(
                blank=True, help_text="Specific date and time for one-off schedules.", null=True, verbose_name="run at"
            ),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekdays", "Weekdays"),
                    ("weekly", "Weekly"),
                    ("custom", "Custom"),
                    ("once", "Once"),
                ],
                default="daily",
                max_length=10,
                verbose_name="frequency",
            ),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekdays", "Weekdays"),
                    ("weekly", "Weekly"),
                    ("custom", "Custom"),
                    ("once", "Once"),
                ],
                default="daily",
                max_length=10,
                verbose_name="frequency",
            ),
        ),
    ]
