# Generated by Django 6.0.4 on 2026-05-11 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sandbox_envs", "0002_seed_global_default"), ("schedules", "0013_oneoff_schedule")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="sandbox_environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_jobs",
                to="sandbox_envs.sandboxenvironment",
                verbose_name="sandbox environment",
            ),
        )
    ]
