# Generated by Django 6.0.5 on 2026-05-22 23:59

from django.db import migrations, models


def _resolve_max_model_spec(apps) -> str:
    SiteConfiguration = apps.get_model("core", "SiteConfiguration")
    config = SiteConfiguration.objects.first()
    if config is not None and getattr(config, "agent_max_model_name", ""):
        return config.agent_max_model_name
    # Match the hardcoded default in core.site_settings._build_field_defaults
    return "openrouter:anthropic/claude-opus-4.6"


def translate_use_max(apps, schema_editor):
    spec = _resolve_max_model_spec(apps)
    for model_name in ("ScheduledJob", "ScheduleTemplate"):
        apps.get_model("schedules", model_name).objects.filter(use_max=True).update(
            agent_model=spec, agent_thinking_level="high"
        )


def reverse_translate_use_max(apps, schema_editor):
    for model_name in ("ScheduledJob", "ScheduleTemplate"):
        apps.get_model("schedules", model_name).objects.exclude(agent_model="").update(use_max=True)


class Migration(migrations.Migration):
    dependencies = [("schedules", "0014_scheduledjob_sandbox_environment"), ("core", "0009_drop_sandbox_overrides")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="agent_model",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="agent model"),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="agent_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[("minimal", "Minimal"), ("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="",
                max_length=20,
                verbose_name="agent thinking level",
            ),
        ),
        migrations.AddField(
            model_name="scheduletemplate",
            name="agent_model",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="agent model"),
        ),
        migrations.AddField(
            model_name="scheduletemplate",
            name="agent_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[("minimal", "Minimal"), ("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="",
                max_length=20,
                verbose_name="agent thinking level",
            ),
        ),
        migrations.RunPython(translate_use_max, reverse_translate_use_max),
    ]
