# Generated by Django 6.0.6 on 2026-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0015_schedules_agent_override_fields")]

    operations = [
        migrations.AlterField(
            model_name="scheduledjob",
            name="agent_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimal", "Minimal"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("xhigh", "Extra high"),
                ],
                default="",
                max_length=20,
                verbose_name="agent thinking level",
            ),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="agent_thinking_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimal", "Minimal"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("xhigh", "Extra high"),
                ],
                default="",
                max_length=20,
                verbose_name="agent thinking level",
            ),
        ),
    ]
