# Generated by Django 6.0.7 on 2026-07-15 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox_envs", "0006_drop_network_enabled"),
        ("schedules", "0016_alter_scheduledjob_agent_thinking_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="intent",
            field=models.CharField(
                choices=[("watch-find", "Watch & find"), ("do-change", "Do & change"), ("report", "Report")],
                default="watch-find",
                help_text="What this schedule is for: watch & find issues, do & change, or just report.",
                max_length=16,
                verbose_name="intent",
            ),
        ),
        migrations.AddField(
            model_name="scheduletemplate",
            name="intent",
            field=models.CharField(
                choices=[("watch-find", "Watch & find"), ("do-change", "Do & change"), ("report", "Report")],
                default="watch-find",
                help_text="What this schedule is for: watch & find issues, do & change, or just report.",
                max_length=16,
                verbose_name="intent",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("intent__in", ["watch-find", "do-change", "report"])), name="sched_intent_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("intent__in", ["watch-find", "do-change", "report"])), name="tpl_intent_valid"
            ),
        ),
    ]
