# Generated by Django 6.0.7 on 2026-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0017_scheduledjob_intent_scheduletemplate_intent_and_more")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="mcp_overrides",
            field=models.JSONField(blank=True, default=dict, verbose_name="MCP overrides"),
        )
    ]
