# Generated by Django 6.0.7 on 2026-08-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0017_scheduledjob_intent_scheduletemplate_intent_and_more")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="muted",
            field=models.BooleanField(
                default=False, help_text="Mute notifications for this schedule.", verbose_name="muted"
            ),
        ),
        migrations.AddField(
            model_name="scheduletemplate",
            name="muted",
            field=models.BooleanField(
                default=False, help_text="Mute notifications for this schedule.", verbose_name="muted"
            ),
        ),
    ]
