# Generated by Django 6.0.7 on 2026-08-09 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("schedules", "0018_add_muted")]

    operations = [
        migrations.RemoveField(model_name="scheduledjob", name="notify_on"),
        migrations.RemoveField(model_name="scheduletemplate", name="notify_on"),
    ]
