# Generated by Django 6.1.1 on 2026-09-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0019_muted_drop_notify_on")]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="dispatch_error",
            field=models.CharField(
                blank=True,
                choices=[("repo_access_denied", "No repository access"), ("unexpected", "Unexpected error")],
                default="",
                max_length=32,
                verbose_name="dispatch error",
            ),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="dispatch_error_repo_ids",
            field=models.JSONField(blank=True, default=list, verbose_name="dispatch error repositories"),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="failing_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of the current run of failed dispatches.",
                null=True,
                verbose_name="failing since",
            ),
        ),
    ]
