# Generated by Django 6.0.7 on 2026-08-20 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("schedules", "0018_scheduledjob_mcp_overrides"), ("schedules", "0019_drop_notify_on")]

    operations = []
