# Generated by Django 6.0.5 on 2026-05-22 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="GlobalSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.SlugField(max_length=80, unique=True, verbose_name="name")),
                ("description", models.CharField(blank=True, default="", max_length=1024, verbose_name="description")),
                ("size_bytes", models.PositiveIntegerField(verbose_name="size (bytes)")),
                ("file_count", models.PositiveIntegerField(verbose_name="file count")),
                ("checksum", models.CharField(max_length=64, verbose_name="checksum")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        )
    ]
