# Generated by Django 6.0.5 on 2026-05-22 23:37

import re

import django.core.validators
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [("skills", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SkillInvocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "name",
                    models.SlugField(
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator(regex=re.compile("^[a-z0-9][a-z0-9-]{0,62}$"))
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("builtin", "Built-in"), ("global", "Custom global"), ("repo", "Per-repo")],
                        max_length=16,
                        verbose_name="source",
                    ),
                ),
                ("repo_slug", models.CharField(max_length=255, verbose_name="repository")),
                ("thread_id", models.UUIDField(verbose_name="thread id")),
            ],
            options={
                "indexes": [models.Index(fields=["name", "source", "-created"], name="skills_skil_name_1c5300_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(repo_slug__gt=""), name="skillinvocation_repo_slug_nonempty"
                    )
                ],
            },
        )
    ]
