#!/bin/bash

set -euo pipefail

postgres_ready() {
uv run python << END
import sys
import traceback
import psycopg
try:
    psycopg.connect(
        dbname="${DB_NAME}",
        user="${DB_USER}",
        password="${DB_PASSWORD}",
        host="${DB_HOST:-localhost}",
        port="${DB_PORT:-5432}",
        sslmode="${DB_SSLMODE:-require}"
    )
except psycopg.OperationalError as e:
    print(e)
    sys.exit(-1)
except Exception:
    traceback.print_exc()
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
  printf 'Waiting for PostgreSQL to become available...\n'
  sleep 1
done
printf 'PostgreSQL is available'

exec "$@"
