#!/bin/sh

set -eu pipefail

django-admin compilemessages --ignore=.venv
django-admin migrate --noinput
django-admin setup_checkpoint_saver

exec uvicorn --host 0.0.0.0 --port 8000 --ssl-keyfile /home/app/src/data/certs/cert.key --ssl-certfile /home/app/src/data/certs/cert.crt --reload --reload-dir 'daiv/' "daiv.asgi:application"
