# Generated by Django 6.0.4 on 2026-04-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0003_user_role")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_on_jobs",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("always", "Always"),
                    ("on_success", "On success only"),
                    ("on_failure", "On failure only"),
                ],
                default="on_failure",
                help_text="When to receive notifications for agent runs you start (UI/API/MCP).",
                max_length=16,
                verbose_name="notify on jobs",
            ),
        )
    ]
