# Generated by Django 6.0.7 on 2026-08-09 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("accounts", "0004_user_notify_on_jobs")]

    operations = [migrations.RemoveField(model_name="user", name="notify_on_jobs")]
