# Generated by Django 6.1 on 2026-09-04 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [("accounts", "0005_drop_notify_on")]

    operations = [
        migrations.CreateModel(
            name="PlatformCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")], max_length=10, verbose_name="provider"
                    ),
                ),
                ("host", models.CharField(max_length=255, verbose_name="host")),
                ("platform_uid", models.CharField(max_length=191, verbose_name="platform user ID")),
                ("_access_token_encrypted", models.TextField(blank=True, null=True, verbose_name="access token")),
                ("_refresh_token_encrypted", models.TextField(blank=True, null=True, verbose_name="refresh token")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="expires at")),
                ("scopes", models.JSONField(blank=True, default=list, verbose_name="granted scopes")),
                (
                    "state",
                    models.CharField(
                        choices=[("connected", "Connected"), ("expired", "Expired"), ("revoked", "Revoked")],
                        default="connected",
                        max_length=10,
                        verbose_name="state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Credential",
                "verbose_name_plural": "Platform Credentials",
                "indexes": [models.Index(fields=["provider", "platform_uid"], name="accounts_pl_provide_d9d0f8_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "provider", "host"), name="platform_credential_unique"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__isnull", True), ("_refresh_token_encrypted__isnull", False), _connector="OR"
                        ),
                        name="platform_credential_expiring_needs_refresh",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "connected"), _negated=True),
                            ("_access_token_encrypted__isnull", False),
                            _connector="OR",
                        ),
                        name="platform_credential_connected_needs_token",
                    ),
                ],
            },
        )
    ]
